//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSB.Service.Web.GenderBulkPG {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="smscitySoap", Namespace="http://rahyabbulk.ir/smsbulk")]
    public partial class smscity : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ProvinceOperationCompleted;
        
        private System.Threading.SendOrPostCallback CityOperationCompleted;
        
        private System.Threading.SendOrPostCallback CellCountOperationCompleted;
        
        private System.Threading.SendOrPostCallback doSendCityBulkOperationCompleted;
        
        private System.Threading.SendOrPostCallback doGetDeliveryOperationCompleted;
        
        private System.Threading.SendOrPostCallback doGetDelivery2OperationCompleted;
        
        private System.Threading.SendOrPostCallback doApproveOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public smscity() {
            this.Url = global::SSB.Service.Web.Properties.Settings.Default.SSB_Service_Web_GenderBulkPG_smscity;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ProvinceCompletedEventHandler ProvinceCompleted;
        
        /// <remarks/>
        public event CityCompletedEventHandler CityCompleted;
        
        /// <remarks/>
        public event CellCountCompletedEventHandler CellCountCompleted;
        
        /// <remarks/>
        public event doSendCityBulkCompletedEventHandler doSendCityBulkCompleted;
        
        /// <remarks/>
        public event doGetDeliveryCompletedEventHandler doGetDeliveryCompleted;
        
        /// <remarks/>
        public event doGetDelivery2CompletedEventHandler doGetDelivery2Completed;
        
        /// <remarks/>
        public event doApproveCompletedEventHandler doApproveCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/Province", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Province() {
            object[] results = this.Invoke("Province", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProvinceAsync() {
            this.ProvinceAsync(null);
        }
        
        /// <remarks/>
        public void ProvinceAsync(object userState) {
            if ((this.ProvinceOperationCompleted == null)) {
                this.ProvinceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProvinceOperationCompleted);
            }
            this.InvokeAsync("Province", new object[0], this.ProvinceOperationCompleted, userState);
        }
        
        private void OnProvinceOperationCompleted(object arg) {
            if ((this.ProvinceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProvinceCompleted(this, new ProvinceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/City", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string City(long Province_ID) {
            object[] results = this.Invoke("City", new object[] {
                        Province_ID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CityAsync(long Province_ID) {
            this.CityAsync(Province_ID, null);
        }
        
        /// <remarks/>
        public void CityAsync(long Province_ID, object userState) {
            if ((this.CityOperationCompleted == null)) {
                this.CityOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCityOperationCompleted);
            }
            this.InvokeAsync("City", new object[] {
                        Province_ID}, this.CityOperationCompleted, userState);
        }
        
        private void OnCityOperationCompleted(object arg) {
            if ((this.CityCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CityCompleted(this, new CityCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/CellCount", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long CellCount(long Province_ID, long City_ID, ref long PrePaid, ref long Women, string FromBirthYear, string ToBirthYear, string PreNumber) {
            object[] results = this.Invoke("CellCount", new object[] {
                        Province_ID,
                        City_ID,
                        PrePaid,
                        Women,
                        FromBirthYear,
                        ToBirthYear,
                        PreNumber});
            PrePaid = ((long)(results[1]));
            Women = ((long)(results[2]));
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void CellCountAsync(long Province_ID, long City_ID, long PrePaid, long Women, string FromBirthYear, string ToBirthYear, string PreNumber) {
            this.CellCountAsync(Province_ID, City_ID, PrePaid, Women, FromBirthYear, ToBirthYear, PreNumber, null);
        }
        
        /// <remarks/>
        public void CellCountAsync(long Province_ID, long City_ID, long PrePaid, long Women, string FromBirthYear, string ToBirthYear, string PreNumber, object userState) {
            if ((this.CellCountOperationCompleted == null)) {
                this.CellCountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCellCountOperationCompleted);
            }
            this.InvokeAsync("CellCount", new object[] {
                        Province_ID,
                        City_ID,
                        PrePaid,
                        Women,
                        FromBirthYear,
                        ToBirthYear,
                        PreNumber}, this.CellCountOperationCompleted, userState);
        }
        
        private void OnCellCountOperationCompleted(object arg) {
            if ((this.CellCountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CellCountCompleted(this, new CellCountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/doSendCityBulk", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string doSendCityBulk(
                    string Username, 
                    string Password, 
                    string ShortCode, 
                    string Message, 
                    string SendDateTime, 
                    long FromRow, 
                    long SMSCount, 
                    bool SortNumber, 
                    int PrePaid, 
                    [System.Xml.Serialization.XmlElementAttribute("Province")] int Province1, 
                    [System.Xml.Serialization.XmlElementAttribute("City")] int City1, 
                    string Prefix, 
                    int Gender, 
                    int FromBirthYear, 
                    int ToBirthYear, 
                    string FirstNumber, 
                    string LastNumber) {
            object[] results = this.Invoke("doSendCityBulk", new object[] {
                        Username,
                        Password,
                        ShortCode,
                        Message,
                        SendDateTime,
                        FromRow,
                        SMSCount,
                        SortNumber,
                        PrePaid,
                        Province1,
                        City1,
                        Prefix,
                        Gender,
                        FromBirthYear,
                        ToBirthYear,
                        FirstNumber,
                        LastNumber});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doSendCityBulkAsync(
                    string Username, 
                    string Password, 
                    string ShortCode, 
                    string Message, 
                    string SendDateTime, 
                    long FromRow, 
                    long SMSCount, 
                    bool SortNumber, 
                    int PrePaid, 
                    int Province1, 
                    int City1, 
                    string Prefix, 
                    int Gender, 
                    int FromBirthYear, 
                    int ToBirthYear, 
                    string FirstNumber, 
                    string LastNumber) {
            this.doSendCityBulkAsync(Username, Password, ShortCode, Message, SendDateTime, FromRow, SMSCount, SortNumber, PrePaid, Province1, City1, Prefix, Gender, FromBirthYear, ToBirthYear, FirstNumber, LastNumber, null);
        }
        
        /// <remarks/>
        public void doSendCityBulkAsync(
                    string Username, 
                    string Password, 
                    string ShortCode, 
                    string Message, 
                    string SendDateTime, 
                    long FromRow, 
                    long SMSCount, 
                    bool SortNumber, 
                    int PrePaid, 
                    int Province1, 
                    int City1, 
                    string Prefix, 
                    int Gender, 
                    int FromBirthYear, 
                    int ToBirthYear, 
                    string FirstNumber, 
                    string LastNumber, 
                    object userState) {
            if ((this.doSendCityBulkOperationCompleted == null)) {
                this.doSendCityBulkOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoSendCityBulkOperationCompleted);
            }
            this.InvokeAsync("doSendCityBulk", new object[] {
                        Username,
                        Password,
                        ShortCode,
                        Message,
                        SendDateTime,
                        FromRow,
                        SMSCount,
                        SortNumber,
                        PrePaid,
                        Province1,
                        City1,
                        Prefix,
                        Gender,
                        FromBirthYear,
                        ToBirthYear,
                        FirstNumber,
                        LastNumber}, this.doSendCityBulkOperationCompleted, userState);
        }
        
        private void OndoSendCityBulkOperationCompleted(object arg) {
            if ((this.doSendCityBulkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doSendCityBulkCompleted(this, new doSendCityBulkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/doGetDelivery", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string doGetDelivery(string Username, long ReturnID) {
            object[] results = this.Invoke("doGetDelivery", new object[] {
                        Username,
                        ReturnID});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doGetDeliveryAsync(string Username, long ReturnID) {
            this.doGetDeliveryAsync(Username, ReturnID, null);
        }
        
        /// <remarks/>
        public void doGetDeliveryAsync(string Username, long ReturnID, object userState) {
            if ((this.doGetDeliveryOperationCompleted == null)) {
                this.doGetDeliveryOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoGetDeliveryOperationCompleted);
            }
            this.InvokeAsync("doGetDelivery", new object[] {
                        Username,
                        ReturnID}, this.doGetDeliveryOperationCompleted, userState);
        }
        
        private void OndoGetDeliveryOperationCompleted(object arg) {
            if ((this.doGetDeliveryCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doGetDeliveryCompleted(this, new doGetDeliveryCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/doGetDelivery2", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string doGetDelivery2(string Username, long ReturnID, ref long SentCount, ref long DeliveredCount) {
            object[] results = this.Invoke("doGetDelivery2", new object[] {
                        Username,
                        ReturnID,
                        SentCount,
                        DeliveredCount});
            SentCount = ((long)(results[1]));
            DeliveredCount = ((long)(results[2]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doGetDelivery2Async(string Username, long ReturnID, long SentCount, long DeliveredCount) {
            this.doGetDelivery2Async(Username, ReturnID, SentCount, DeliveredCount, null);
        }
        
        /// <remarks/>
        public void doGetDelivery2Async(string Username, long ReturnID, long SentCount, long DeliveredCount, object userState) {
            if ((this.doGetDelivery2OperationCompleted == null)) {
                this.doGetDelivery2OperationCompleted = new System.Threading.SendOrPostCallback(this.OndoGetDelivery2OperationCompleted);
            }
            this.InvokeAsync("doGetDelivery2", new object[] {
                        Username,
                        ReturnID,
                        SentCount,
                        DeliveredCount}, this.doGetDelivery2OperationCompleted, userState);
        }
        
        private void OndoGetDelivery2OperationCompleted(object arg) {
            if ((this.doGetDelivery2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doGetDelivery2Completed(this, new doGetDelivery2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://rahyabbulk.ir/smsbulk/doApprove", RequestNamespace="http://rahyabbulk.ir/smsbulk", ResponseNamespace="http://rahyabbulk.ir/smsbulk", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string doApprove(string Username, long ReturnID, bool Approve) {
            object[] results = this.Invoke("doApprove", new object[] {
                        Username,
                        ReturnID,
                        Approve});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void doApproveAsync(string Username, long ReturnID, bool Approve) {
            this.doApproveAsync(Username, ReturnID, Approve, null);
        }
        
        /// <remarks/>
        public void doApproveAsync(string Username, long ReturnID, bool Approve, object userState) {
            if ((this.doApproveOperationCompleted == null)) {
                this.doApproveOperationCompleted = new System.Threading.SendOrPostCallback(this.OndoApproveOperationCompleted);
            }
            this.InvokeAsync("doApprove", new object[] {
                        Username,
                        ReturnID,
                        Approve}, this.doApproveOperationCompleted, userState);
        }
        
        private void OndoApproveOperationCompleted(object arg) {
            if ((this.doApproveCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.doApproveCompleted(this, new doApproveCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void ProvinceCompletedEventHandler(object sender, ProvinceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProvinceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProvinceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CityCompletedEventHandler(object sender, CityCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CityCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CityCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void CellCountCompletedEventHandler(object sender, CellCountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CellCountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CellCountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long PrePaid {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public long Women {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doSendCityBulkCompletedEventHandler(object sender, doSendCityBulkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doSendCityBulkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doSendCityBulkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doGetDeliveryCompletedEventHandler(object sender, doGetDeliveryCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doGetDeliveryCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doGetDeliveryCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doGetDelivery2CompletedEventHandler(object sender, doGetDelivery2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doGetDelivery2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doGetDelivery2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public long SentCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public long DeliveredCount {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void doApproveCompletedEventHandler(object sender, doApproveCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class doApproveCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal doApproveCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591