//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SSB.Service.Web.RahyabService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RahyabSPCSendServiceSoap", Namespace="http://tempuri.org/")]
    public partial class RahyabSPCSendService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetPostalCityCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback MCI_PostalSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetGlobalProvinceCodeOperationCompleted;
        
        private System.Threading.SendOrPostCallback MCI_GlobalSendOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetStatus_MCISendOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RahyabSPCSendService() {
            this.Url = global::SSB.Service.Web.Properties.Settings.Default.SSB_Service_Web_RahyabService_RahyabSPCSendService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetPostalCityCodeCompletedEventHandler GetPostalCityCodeCompleted;
        
        /// <remarks/>
        public event MCI_PostalSendCompletedEventHandler MCI_PostalSendCompleted;
        
        /// <remarks/>
        public event GetGlobalProvinceCodeCompletedEventHandler GetGlobalProvinceCodeCompleted;
        
        /// <remarks/>
        public event MCI_GlobalSendCompletedEventHandler MCI_GlobalSendCompleted;
        
        /// <remarks/>
        public event GetStatus_MCISendCompletedEventHandler GetStatus_MCISendCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetPostalCityCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetPostalCityCode(string strCityName, ref string strMessage) {
            object[] results = this.Invoke("GetPostalCityCode", new object[] {
                        strCityName,
                        strMessage});
            strMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetPostalCityCodeAsync(string strCityName, string strMessage) {
            this.GetPostalCityCodeAsync(strCityName, strMessage, null);
        }
        
        /// <remarks/>
        public void GetPostalCityCodeAsync(string strCityName, string strMessage, object userState) {
            if ((this.GetPostalCityCodeOperationCompleted == null)) {
                this.GetPostalCityCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetPostalCityCodeOperationCompleted);
            }
            this.InvokeAsync("GetPostalCityCode", new object[] {
                        strCityName,
                        strMessage}, this.GetPostalCityCodeOperationCompleted, userState);
        }
        
        private void OnGetPostalCityCodeOperationCompleted(object arg) {
            if ((this.GetPostalCityCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetPostalCityCodeCompleted(this, new GetPostalCityCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MCI_PostalSend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MCI_PostalSend(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, string MessageText, int intSelectType, int intCityID, int intAreaCode, int intRegionCode, int intFrom, int intTo, int intCount, ref string strMessage) {
            object[] results = this.Invoke("MCI_PostalSend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        MessageText,
                        intSelectType,
                        intCityID,
                        intAreaCode,
                        intRegionCode,
                        intFrom,
                        intTo,
                        intCount,
                        strMessage});
            strMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MCI_PostalSendAsync(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, string MessageText, int intSelectType, int intCityID, int intAreaCode, int intRegionCode, int intFrom, int intTo, int intCount, string strMessage) {
            this.MCI_PostalSendAsync(strNumber, strGatewayUserName, strGatewayPassword, strGatewayCompany, MessageText, intSelectType, intCityID, intAreaCode, intRegionCode, intFrom, intTo, intCount, strMessage, null);
        }
        
        /// <remarks/>
        public void MCI_PostalSendAsync(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, string MessageText, int intSelectType, int intCityID, int intAreaCode, int intRegionCode, int intFrom, int intTo, int intCount, string strMessage, object userState) {
            if ((this.MCI_PostalSendOperationCompleted == null)) {
                this.MCI_PostalSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMCI_PostalSendOperationCompleted);
            }
            this.InvokeAsync("MCI_PostalSend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        MessageText,
                        intSelectType,
                        intCityID,
                        intAreaCode,
                        intRegionCode,
                        intFrom,
                        intTo,
                        intCount,
                        strMessage}, this.MCI_PostalSendOperationCompleted, userState);
        }
        
        private void OnMCI_PostalSendOperationCompleted(object arg) {
            if ((this.MCI_PostalSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MCI_PostalSendCompleted(this, new MCI_PostalSendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetGlobalProvinceCode", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int GetGlobalProvinceCode(string strProvinceName, ref string strMessage) {
            object[] results = this.Invoke("GetGlobalProvinceCode", new object[] {
                        strProvinceName,
                        strMessage});
            strMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void GetGlobalProvinceCodeAsync(string strProvinceName, string strMessage) {
            this.GetGlobalProvinceCodeAsync(strProvinceName, strMessage, null);
        }
        
        /// <remarks/>
        public void GetGlobalProvinceCodeAsync(string strProvinceName, string strMessage, object userState) {
            if ((this.GetGlobalProvinceCodeOperationCompleted == null)) {
                this.GetGlobalProvinceCodeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetGlobalProvinceCodeOperationCompleted);
            }
            this.InvokeAsync("GetGlobalProvinceCode", new object[] {
                        strProvinceName,
                        strMessage}, this.GetGlobalProvinceCodeOperationCompleted, userState);
        }
        
        private void OnGetGlobalProvinceCodeOperationCompleted(object arg) {
            if ((this.GetGlobalProvinceCodeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetGlobalProvinceCodeCompleted(this, new GetGlobalProvinceCodeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/MCI_GlobalSend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public int MCI_GlobalSend(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, string MessageText, int intSelectType, int intProvinceID, string strCityName, bool blnNumberType, int intOnePreCode, int intThreeCode, int intFrom, int intTo, int intCount, ref string strMessage) {
            object[] results = this.Invoke("MCI_GlobalSend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        MessageText,
                        intSelectType,
                        intProvinceID,
                        strCityName,
                        blnNumberType,
                        intOnePreCode,
                        intThreeCode,
                        intFrom,
                        intTo,
                        intCount,
                        strMessage});
            strMessage = ((string)(results[1]));
            return ((int)(results[0]));
        }
        
        /// <remarks/>
        public void MCI_GlobalSendAsync(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, string MessageText, int intSelectType, int intProvinceID, string strCityName, bool blnNumberType, int intOnePreCode, int intThreeCode, int intFrom, int intTo, int intCount, string strMessage) {
            this.MCI_GlobalSendAsync(strNumber, strGatewayUserName, strGatewayPassword, strGatewayCompany, MessageText, intSelectType, intProvinceID, strCityName, blnNumberType, intOnePreCode, intThreeCode, intFrom, intTo, intCount, strMessage, null);
        }
        
        /// <remarks/>
        public void MCI_GlobalSendAsync(
                    string strNumber, 
                    string strGatewayUserName, 
                    string strGatewayPassword, 
                    string strGatewayCompany, 
                    string MessageText, 
                    int intSelectType, 
                    int intProvinceID, 
                    string strCityName, 
                    bool blnNumberType, 
                    int intOnePreCode, 
                    int intThreeCode, 
                    int intFrom, 
                    int intTo, 
                    int intCount, 
                    string strMessage, 
                    object userState) {
            if ((this.MCI_GlobalSendOperationCompleted == null)) {
                this.MCI_GlobalSendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMCI_GlobalSendOperationCompleted);
            }
            this.InvokeAsync("MCI_GlobalSend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        MessageText,
                        intSelectType,
                        intProvinceID,
                        strCityName,
                        blnNumberType,
                        intOnePreCode,
                        intThreeCode,
                        intFrom,
                        intTo,
                        intCount,
                        strMessage}, this.MCI_GlobalSendOperationCompleted, userState);
        }
        
        private void OnMCI_GlobalSendOperationCompleted(object arg) {
            if ((this.MCI_GlobalSendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MCI_GlobalSendCompleted(this, new MCI_GlobalSendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetStatus_MCISend", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetStatus_MCISend(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, int intSPCSnedID, ref string strMessage) {
            object[] results = this.Invoke("GetStatus_MCISend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        intSPCSnedID,
                        strMessage});
            strMessage = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetStatus_MCISendAsync(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, int intSPCSnedID, string strMessage) {
            this.GetStatus_MCISendAsync(strNumber, strGatewayUserName, strGatewayPassword, strGatewayCompany, intSPCSnedID, strMessage, null);
        }
        
        /// <remarks/>
        public void GetStatus_MCISendAsync(string strNumber, string strGatewayUserName, string strGatewayPassword, string strGatewayCompany, int intSPCSnedID, string strMessage, object userState) {
            if ((this.GetStatus_MCISendOperationCompleted == null)) {
                this.GetStatus_MCISendOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetStatus_MCISendOperationCompleted);
            }
            this.InvokeAsync("GetStatus_MCISend", new object[] {
                        strNumber,
                        strGatewayUserName,
                        strGatewayPassword,
                        strGatewayCompany,
                        intSPCSnedID,
                        strMessage}, this.GetStatus_MCISendOperationCompleted, userState);
        }
        
        private void OnGetStatus_MCISendOperationCompleted(object arg) {
            if ((this.GetStatus_MCISendCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetStatus_MCISendCompleted(this, new GetStatus_MCISendCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetPostalCityCodeCompletedEventHandler(object sender, GetPostalCityCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetPostalCityCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetPostalCityCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MCI_PostalSendCompletedEventHandler(object sender, MCI_PostalSendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MCI_PostalSendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MCI_PostalSendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetGlobalProvinceCodeCompletedEventHandler(object sender, GetGlobalProvinceCodeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetGlobalProvinceCodeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetGlobalProvinceCodeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void MCI_GlobalSendCompletedEventHandler(object sender, MCI_GlobalSendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MCI_GlobalSendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MCI_GlobalSendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void GetStatus_MCISendCompletedEventHandler(object sender, GetStatus_MCISendCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetStatus_MCISendCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetStatus_MCISendCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string strMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591