//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using SSB.Core.Data;

using System.Data.Entity.Core.Objects;

namespace SSB.Service.Core
{
    public partial class AcountingEntities : MainContext
    {
        public AcountingEntities()
            : base("name=AcountingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CreditLog> CreditLogs { get; set; }
        public DbSet<UserAccount> UserAccounts { get; set; }
        public DbSet<Tbl_UsrCredit> Tbl_UsrCredit { get; set; }
        public DbSet<Bulk_RequestAcc> Bulk_RequestAcc { get; set; }
        public DbSet<BulkAcc> BulkAccs { get; set; }
        public DbSet<Tbl_BulkSendingDefinition> Tbl_BulkSendingDefinition { get; set; }
        public DbSet<linenumber> Tbl_LineNumber { get; set; }
        public DbSet<ReservedLineNumbers> ReservedLineNumbers { get; set; }
        public DbSet<Ticket> Ticket { get; set; }
        public DbSet<VASContent> VASContent { get; set; }
        public DbSet<Customers> Customers { get; set; }
        public DbSet<VASService> VASService { get; set; }
        public DbSet<tbl_Extensible> tbl_Extensible { get; set; }
    
        public virtual ObjectResult<Nullable<int>> SPTbl_Bulk_Delete(Nullable<int> bulkId)
        {
            var bulkIdParameter = bulkId.HasValue ?
                new ObjectParameter("BulkId", bulkId) :
                new ObjectParameter("BulkId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SPTbl_Bulk_Delete", bulkIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> SpTbl_Payment_Insert(string iUsrId, Nullable<int> payTypeCode, Nullable<int> payCommentCode, Nullable<int> paymentAmount, Nullable<byte> paymentDiscount, string payDisComment, string paySerial, string paymentDate, string payExpiredDate, Nullable<bool> payFlag)
        {
            var iUsrIdParameter = iUsrId != null ?
                new ObjectParameter("IUsrId", iUsrId) :
                new ObjectParameter("IUsrId", typeof(string));
    
            var payTypeCodeParameter = payTypeCode.HasValue ?
                new ObjectParameter("PayTypeCode", payTypeCode) :
                new ObjectParameter("PayTypeCode", typeof(int));
    
            var payCommentCodeParameter = payCommentCode.HasValue ?
                new ObjectParameter("PayCommentCode", payCommentCode) :
                new ObjectParameter("PayCommentCode", typeof(int));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("PaymentAmount", paymentAmount) :
                new ObjectParameter("PaymentAmount", typeof(int));
    
            var paymentDiscountParameter = paymentDiscount.HasValue ?
                new ObjectParameter("PaymentDiscount", paymentDiscount) :
                new ObjectParameter("PaymentDiscount", typeof(byte));
    
            var payDisCommentParameter = payDisComment != null ?
                new ObjectParameter("PayDisComment", payDisComment) :
                new ObjectParameter("PayDisComment", typeof(string));
    
            var paySerialParameter = paySerial != null ?
                new ObjectParameter("PaySerial", paySerial) :
                new ObjectParameter("PaySerial", typeof(string));
    
            var paymentDateParameter = paymentDate != null ?
                new ObjectParameter("PaymentDate", paymentDate) :
                new ObjectParameter("PaymentDate", typeof(string));
    
            var payExpiredDateParameter = payExpiredDate != null ?
                new ObjectParameter("PayExpiredDate", payExpiredDate) :
                new ObjectParameter("PayExpiredDate", typeof(string));
    
            var payFlagParameter = payFlag.HasValue ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("SpTbl_Payment_Insert", iUsrIdParameter, payTypeCodeParameter, payCommentCodeParameter, paymentAmountParameter, paymentDiscountParameter, payDisCommentParameter, paySerialParameter, paymentDateParameter, payExpiredDateParameter, payFlagParameter);
        }
    
        public virtual ObjectResult<string> SpTbl_OnlineUsrCredit_Insert_ForAdminCharj(string iUsrId, Nullable<int> payTypeCode, Nullable<int> paymentAmount, string paymentDate, Nullable<bool> payFlag, Nullable<int> iSMSFaPrice, Nullable<int> iSMSEnPrice, Nullable<int> iRcvSmsPrice, Nullable<System.DateTime> payDate, string transactionNumber, Nullable<int> bankId, string invoiceNumber, string description, Nullable<bool> isFrist)
        {
            var iUsrIdParameter = iUsrId != null ?
                new ObjectParameter("IUsrId", iUsrId) :
                new ObjectParameter("IUsrId", typeof(string));
    
            var payTypeCodeParameter = payTypeCode.HasValue ?
                new ObjectParameter("PayTypeCode", payTypeCode) :
                new ObjectParameter("PayTypeCode", typeof(int));
    
            var paymentAmountParameter = paymentAmount.HasValue ?
                new ObjectParameter("PaymentAmount", paymentAmount) :
                new ObjectParameter("PaymentAmount", typeof(int));
    
            var paymentDateParameter = paymentDate != null ?
                new ObjectParameter("PaymentDate", paymentDate) :
                new ObjectParameter("PaymentDate", typeof(string));
    
            var payFlagParameter = payFlag.HasValue ?
                new ObjectParameter("PayFlag", payFlag) :
                new ObjectParameter("PayFlag", typeof(bool));
    
            var iSMSFaPriceParameter = iSMSFaPrice.HasValue ?
                new ObjectParameter("ISMSFaPrice", iSMSFaPrice) :
                new ObjectParameter("ISMSFaPrice", typeof(int));
    
            var iSMSEnPriceParameter = iSMSEnPrice.HasValue ?
                new ObjectParameter("ISMSEnPrice", iSMSEnPrice) :
                new ObjectParameter("ISMSEnPrice", typeof(int));
    
            var iRcvSmsPriceParameter = iRcvSmsPrice.HasValue ?
                new ObjectParameter("IRcvSmsPrice", iRcvSmsPrice) :
                new ObjectParameter("IRcvSmsPrice", typeof(int));
    
            var payDateParameter = payDate.HasValue ?
                new ObjectParameter("PayDate", payDate) :
                new ObjectParameter("PayDate", typeof(System.DateTime));
    
            var transactionNumberParameter = transactionNumber != null ?
                new ObjectParameter("TransactionNumber", transactionNumber) :
                new ObjectParameter("TransactionNumber", typeof(string));
    
            var bankIdParameter = bankId.HasValue ?
                new ObjectParameter("BankId", bankId) :
                new ObjectParameter("BankId", typeof(int));
    
            var invoiceNumberParameter = invoiceNumber != null ?
                new ObjectParameter("InvoiceNumber", invoiceNumber) :
                new ObjectParameter("InvoiceNumber", typeof(string));
    
            var descriptionParameter = description != null ?
                new ObjectParameter("Description", description) :
                new ObjectParameter("Description", typeof(string));
    
            var isFristParameter = isFrist.HasValue ?
                new ObjectParameter("IsFrist", isFrist) :
                new ObjectParameter("IsFrist", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SpTbl_OnlineUsrCredit_Insert_ForAdminCharj", iUsrIdParameter, payTypeCodeParameter, paymentAmountParameter, paymentDateParameter, payFlagParameter, iSMSFaPriceParameter, iSMSEnPriceParameter, iRcvSmsPriceParameter, payDateParameter, transactionNumberParameter, bankIdParameter, invoiceNumberParameter, descriptionParameter, isFristParameter);
        }
    }
}
