//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Bulk_Request))]
    [KnownType(typeof(Tbl_LineNumber))]
    [KnownType(typeof(Tbl_UserAccount))]
    public partial class Bulk: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int BulkId
        {
            get { return _bulkId; }
            set
            {
                if (_bulkId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'BulkId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _bulkId = value;
                    OnPropertyChanged("BulkId");
                }
            }
        }
        private int _bulkId;
    
        [DataMember]
        public Nullable<int> LineNumberCode
        {
            get { return _lineNumberCode; }
            set
            {
                if (_lineNumberCode != value)
                {
                    ChangeTracker.RecordOriginalValue("LineNumberCode", _lineNumberCode);
                    if (!IsDeserializing)
                    {
                        if (Tbl_LineNumber != null && Tbl_LineNumber.ILineNumberCode != value)
                        {
                            Tbl_LineNumber = null;
                        }
                    }
                    _lineNumberCode = value;
                    OnPropertyChanged("LineNumberCode");
                }
            }
        }
        private Nullable<int> _lineNumberCode;
    
        [DataMember]
        public string BulkText
        {
            get { return _bulkText; }
            set
            {
                if (_bulkText != value)
                {
                    _bulkText = value;
                    OnPropertyChanged("BulkText");
                }
            }
        }
        private string _bulkText;
    
        [DataMember]
        public Nullable<System.DateTime> SendDate
        {
            get { return _sendDate; }
            set
            {
                if (_sendDate != value)
                {
                    _sendDate = value;
                    OnPropertyChanged("SendDate");
                }
            }
        }
        private Nullable<System.DateTime> _sendDate;
    
        [DataMember]
        public Nullable<byte> SendingType
        {
            get { return _sendingType; }
            set
            {
                if (_sendingType != value)
                {
                    _sendingType = value;
                    OnPropertyChanged("SendingType");
                }
            }
        }
        private Nullable<byte> _sendingType;
    
        [DataMember]
        public Nullable<bool> IsPersian
        {
            get { return _isPersian; }
            set
            {
                if (_isPersian != value)
                {
                    _isPersian = value;
                    OnPropertyChanged("IsPersian");
                }
            }
        }
        private Nullable<bool> _isPersian;
    
        [DataMember]
        public Nullable<byte> Status
        {
            get { return _status; }
            set
            {
                if (_status != value)
                {
                    _status = value;
                    OnPropertyChanged("Status");
                }
            }
        }
        private Nullable<byte> _status;
    
        [DataMember]
        public string AdminNote
        {
            get { return _adminNote; }
            set
            {
                if (_adminNote != value)
                {
                    _adminNote = value;
                    OnPropertyChanged("AdminNote");
                }
            }
        }
        private string _adminNote;
    
        [DataMember]
        public Nullable<int> TotalPrice
        {
            get { return _totalPrice; }
            set
            {
                if (_totalPrice != value)
                {
                    _totalPrice = value;
                    OnPropertyChanged("TotalPrice");
                }
            }
        }
        private Nullable<int> _totalPrice;
    
        [DataMember]
        public Nullable<System.DateTime> RequestDate
        {
            get { return _requestDate; }
            set
            {
                if (_requestDate != value)
                {
                    _requestDate = value;
                    OnPropertyChanged("RequestDate");
                }
            }
        }
        private Nullable<System.DateTime> _requestDate;
    
        [DataMember]
        public string UserId
        {
            get { return _userId; }
            set
            {
                if (_userId != value)
                {
                    ChangeTracker.RecordOriginalValue("UserId", _userId);
                    if (!IsDeserializing)
                    {
                        if (Tbl_UserAccount != null && Tbl_UserAccount.IUsrId != value)
                        {
                            Tbl_UserAccount = null;
                        }
                    }
                    _userId = value;
                    OnPropertyChanged("UserId");
                }
            }
        }
        private string _userId;
    
        [DataMember]
        public Nullable<System.DateTime> ModifiedDate
        {
            get { return _modifiedDate; }
            set
            {
                if (_modifiedDate != value)
                {
                    _modifiedDate = value;
                    OnPropertyChanged("ModifiedDate");
                }
            }
        }
        private Nullable<System.DateTime> _modifiedDate;
    
        [DataMember]
        public string ModifyBy
        {
            get { return _modifyBy; }
            set
            {
                if (_modifyBy != value)
                {
                    _modifyBy = value;
                    OnPropertyChanged("ModifyBy");
                }
            }
        }
        private string _modifyBy;
    
        [DataMember]
        public string Notation
        {
            get { return _notation; }
            set
            {
                if (_notation != value)
                {
                    _notation = value;
                    OnPropertyChanged("Notation");
                }
            }
        }
        private string _notation;
    
        [DataMember]
        public Nullable<bool> ReturnCredit
        {
            get { return _returnCredit; }
            set
            {
                if (_returnCredit != value)
                {
                    _returnCredit = value;
                    OnPropertyChanged("ReturnCredit");
                }
            }
        }
        private Nullable<bool> _returnCredit;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Bulk_Request> Bulk_Request
        {
            get
            {
                if (_bulk_Request == null)
                {
                    _bulk_Request = new TrackableCollection<Bulk_Request>();
                    _bulk_Request.CollectionChanged += FixupBulk_Request;
                }
                return _bulk_Request;
            }
            set
            {
                if (!ReferenceEquals(_bulk_Request, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bulk_Request != null)
                    {
                        _bulk_Request.CollectionChanged -= FixupBulk_Request;
                    }
                    _bulk_Request = value;
                    if (_bulk_Request != null)
                    {
                        _bulk_Request.CollectionChanged += FixupBulk_Request;
                    }
                    OnNavigationPropertyChanged("Bulk_Request");
                }
            }
        }
        private TrackableCollection<Bulk_Request> _bulk_Request;
    
        [DataMember]
        public Tbl_LineNumber Tbl_LineNumber
        {
            get { return _tbl_LineNumber; }
            set
            {
                if (!ReferenceEquals(_tbl_LineNumber, value))
                {
                    var previousValue = _tbl_LineNumber;
                    _tbl_LineNumber = value;
                    FixupTbl_LineNumber(previousValue);
                    OnNavigationPropertyChanged("Tbl_LineNumber");
                }
            }
        }
        private Tbl_LineNumber _tbl_LineNumber;
    
        [DataMember]
        public Tbl_UserAccount Tbl_UserAccount
        {
            get { return _tbl_UserAccount; }
            set
            {
                if (!ReferenceEquals(_tbl_UserAccount, value))
                {
                    var previousValue = _tbl_UserAccount;
                    _tbl_UserAccount = value;
                    FixupTbl_UserAccount(previousValue);
                    OnNavigationPropertyChanged("Tbl_UserAccount");
                }
            }
        }
        private Tbl_UserAccount _tbl_UserAccount;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Bulk_Request.Clear();
            Tbl_LineNumber = null;
            Tbl_UserAccount = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_LineNumber(Tbl_LineNumber previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Bulks.Contains(this))
            {
                previousValue.Bulks.Remove(this);
            }
    
            if (Tbl_LineNumber != null)
            {
                if (!Tbl_LineNumber.Bulks.Contains(this))
                {
                    Tbl_LineNumber.Bulks.Add(this);
                }
    
                LineNumberCode = Tbl_LineNumber.ILineNumberCode;
            }
            else if (!skipKeys)
            {
                LineNumberCode = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_LineNumber")
                    && (ChangeTracker.OriginalValues["Tbl_LineNumber"] == Tbl_LineNumber))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_LineNumber");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_LineNumber", previousValue);
                }
                if (Tbl_LineNumber != null && !Tbl_LineNumber.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_LineNumber.StartTracking();
                }
            }
        }
    
        private void FixupTbl_UserAccount(Tbl_UserAccount previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Bulks.Contains(this))
            {
                previousValue.Bulks.Remove(this);
            }
    
            if (Tbl_UserAccount != null)
            {
                if (!Tbl_UserAccount.Bulks.Contains(this))
                {
                    Tbl_UserAccount.Bulks.Add(this);
                }
    
                UserId = Tbl_UserAccount.IUsrId;
            }
            else if (!skipKeys)
            {
                UserId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_UserAccount")
                    && (ChangeTracker.OriginalValues["Tbl_UserAccount"] == Tbl_UserAccount))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_UserAccount");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_UserAccount", previousValue);
                }
                if (Tbl_UserAccount != null && !Tbl_UserAccount.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_UserAccount.StartTracking();
                }
            }
        }
    
        private void FixupBulk_Request(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Bulk_Request item in e.NewItems)
                {
                    item.Bulk = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Bulk_Request", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Bulk_Request item in e.OldItems)
                {
                    if (ReferenceEquals(item.Bulk, this))
                    {
                        item.Bulk = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Bulk_Request", item);
                    }
                }
            }
        }

        #endregion

    }
}
