//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class Bulk_RequestAcc
    {
        public int BulkRequestId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> StartIndex { get; set; }
        public Nullable<int> RequestCount { get; set; }
        public Nullable<int> BulkId { get; set; }
        public string BulkValue { get; set; }
        public Nullable<int> ValueType { get; set; }
        public Nullable<int> ValueOperation { get; set; }
        public byte PhoneType { get; set; }
    
        public virtual BulkAcc Bulk { get; set; }
    }
    
}
