//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Bulk))]
    public partial class Bulk_Request: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int BulkRequestId
        {
            get { return _bulkRequestId; }
            set
            {
                if (_bulkRequestId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'BulkRequestId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _bulkRequestId = value;
                    OnPropertyChanged("BulkRequestId");
                }
            }
        }
        private int _bulkRequestId;
    
        [DataMember]
        public Nullable<int> CategoryId
        {
            get { return _categoryId; }
            set
            {
                if (_categoryId != value)
                {
                    _categoryId = value;
                    OnPropertyChanged("CategoryId");
                }
            }
        }
        private Nullable<int> _categoryId;
    
        [DataMember]
        public Nullable<int> StartIndex
        {
            get { return _startIndex; }
            set
            {
                if (_startIndex != value)
                {
                    _startIndex = value;
                    OnPropertyChanged("StartIndex");
                }
            }
        }
        private Nullable<int> _startIndex;
    
        [DataMember]
        public Nullable<int> RequestCount
        {
            get { return _requestCount; }
            set
            {
                if (_requestCount != value)
                {
                    _requestCount = value;
                    OnPropertyChanged("RequestCount");
                }
            }
        }
        private Nullable<int> _requestCount;
    
        [DataMember]
        public Nullable<int> BulkId
        {
            get { return _bulkId; }
            set
            {
                if (_bulkId != value)
                {
                    ChangeTracker.RecordOriginalValue("BulkId", _bulkId);
                    if (!IsDeserializing)
                    {
                        if (Bulk != null && Bulk.BulkId != value)
                        {
                            Bulk = null;
                        }
                    }
                    _bulkId = value;
                    OnPropertyChanged("BulkId");
                }
            }
        }
        private Nullable<int> _bulkId;
    
        [DataMember]
        public string BulkValue
        {
            get { return _bulkValue; }
            set
            {
                if (_bulkValue != value)
                {
                    _bulkValue = value;
                    OnPropertyChanged("BulkValue");
                }
            }
        }
        private string _bulkValue;
    
        [DataMember]
        public Nullable<int> ValueType
        {
            get { return _valueType; }
            set
            {
                if (_valueType != value)
                {
                    _valueType = value;
                    OnPropertyChanged("ValueType");
                }
            }
        }
        private Nullable<int> _valueType;
    
        [DataMember]
        public Nullable<int> ValueOperation
        {
            get { return _valueOperation; }
            set
            {
                if (_valueOperation != value)
                {
                    _valueOperation = value;
                    OnPropertyChanged("ValueOperation");
                }
            }
        }
        private Nullable<int> _valueOperation;
    
        [DataMember]
        public byte PhoneType
        {
            get { return _phoneType; }
            set
            {
                if (_phoneType != value)
                {
                    _phoneType = value;
                    OnPropertyChanged("PhoneType");
                }
            }
        }
        private byte _phoneType;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Bulk Bulk
        {
            get { return _bulk; }
            set
            {
                if (!ReferenceEquals(_bulk, value))
                {
                    var previousValue = _bulk;
                    _bulk = value;
                    FixupBulk(previousValue);
                    OnNavigationPropertyChanged("Bulk");
                }
            }
        }
        private Bulk _bulk;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Bulk = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupBulk(Bulk previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Bulk_Request.Contains(this))
            {
                previousValue.Bulk_Request.Remove(this);
            }
    
            if (Bulk != null)
            {
                if (!Bulk.Bulk_Request.Contains(this))
                {
                    Bulk.Bulk_Request.Add(this);
                }
    
                BulkId = Bulk.BulkId;
            }
            else if (!skipKeys)
            {
                BulkId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Bulk")
                    && (ChangeTracker.OriginalValues["Bulk"] == Bulk))
                {
                    ChangeTracker.OriginalValues.Remove("Bulk");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Bulk", previousValue);
                }
                if (Bulk != null && !Bulk.ChangeTracker.ChangeTrackingEnabled)
                {
                    Bulk.StartTracking();
                }
            }
        }

        #endregion

    }
}
