//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class BulkAcc
    {
        public BulkAcc()
        {
            this.Bulk_Request = new HashSet<Bulk_RequestAcc>();
        }
    
        public int BulkId { get; set; }
        public Nullable<int> LineNumberCode { get; set; }
        public string BulkText { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<byte> SendingType { get; set; }
        public Nullable<bool> IsPersian { get; set; }
        public Nullable<byte> Status { get; set; }
        public string AdminNote { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<System.DateTime> RequestDate { get; set; }
        public string UserId { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string ModifyBy { get; set; }
        public string Notation { get; set; }
        public Nullable<bool> ReturnCredit { get; set; }
    
        public virtual ICollection<Bulk_RequestAcc> Bulk_Request { get; set; }
        public virtual UserAccount Tbl_UserAccount { get; set; }
        public virtual linenumber Tbl_LineNumber { get; set; }
    }
    
}
