//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class CreditLog
    {
        public long Id { get; set; }
        public long Amount { get; set; }
        public string UserName { get; set; }
        public string Action { get; set; }
        public System.DateTime Date { get; set; }
        public int FaPrice { get; set; }
        public int EnPrice { get; set; }
        public Nullable<int> PaymentId { get; set; }
        public Nullable<int> EnSmsCount { get; set; }
        public Nullable<int> FaSmsCount { get; set; }
        public string Source { get; set; }
        public Nullable<int> TotalCredit { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsIncrease { get; set; }
    }
    
}
