//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class Customers
    {
        public Customers()
        {
            this.Tbl_UserAccount = new HashSet<UserAccount>();
        }
    
        public int ICCode { get; set; }
        public Nullable<int> ICParentID { get; set; }
        public Nullable<int> IProviencyCode { get; set; }
        public Nullable<int> ICityCode { get; set; }
        public Nullable<int> IActTypeCode { get; set; }
        public string ICName { get; set; }
        public string ICLName { get; set; }
        public string ICTel { get; set; }
        public string ICMobile { get; set; }
        public string ICFax { get; set; }
        public string ICEmail { get; set; }
        public string ICWebSite { get; set; }
        public string ICPrsAdrs { get; set; }
        public string ICZipeCode { get; set; }
        public string ICCoName { get; set; }
        public Nullable<bool> ICCoType { get; set; }
        public string ICCoActivity { get; set; }
        public string ICDescrtiption { get; set; }
        public string ICPrsNumber { get; set; }
        public string ICMeliCartPic { get; set; }
        public string ICPrsNumberPic { get; set; }
    
        public virtual ICollection<UserAccount> Tbl_UserAccount { get; set; }
    }
    
}
