//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class linenumber
    {
        public linenumber()
        {
            this.Bulks = new HashSet<BulkAcc>();
        }
    
        public int ILineNumberCode { get; set; }
        public string IUsrId { get; set; }
        public string ILineNumber { get; set; }
        public string ILineModuleNumber { get; set; }
        public string ILineServiceType { get; set; }
        public string ILineKeyWord { get; set; }
        public string ILineStatuse { get; set; }
        public string ILineLastModify { get; set; }
        public string ILineDuration { get; set; }
    
        public virtual ICollection<BulkAcc> Bulks { get; set; }
        public virtual UserAccount Tbl_UserAccount { get; set; }
    }
    
}
