//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data.Common;
using System.Data.EntityClient;
using System.Data.Metadata.Edm;
using System.Data.Objects.DataClasses;
using System.Data.Objects;
using System.Data;
using System.Diagnostics;
using System.Globalization;
using System.Linq;

namespace SSB.Service.Core
{
    public partial class SMSModelContainer : ObjectContext
    {
        public const string ConnectionString = "name=SMSModelContainer";
        public const string ContainerName = "SMSModelContainer";
    
        #region Constructors
    
        public SMSModelContainer()
            : base(ConnectionString, ContainerName)
        {
            Initialize();
        }
    
        public SMSModelContainer(string connectionString)
            : base(connectionString, ContainerName)
        {
            Initialize();
        }
    
        public SMSModelContainer(EntityConnection connection)
            : base(connection, ContainerName)
        {
            Initialize();
        }
    
        private void Initialize()
        {
            // Creating proxies requires the use of the ProxyDataContractResolver and
            // may allow lazy loading which can expand the loaded graph during serialization.
            ContextOptions.ProxyCreationEnabled = false;
            ObjectMaterialized += new ObjectMaterializedEventHandler(HandleObjectMaterialized);
        }
    
        private void HandleObjectMaterialized(object sender, ObjectMaterializedEventArgs e)
        {
            var entity = e.Entity as IObjectWithChangeTracker;
            if (entity != null)
            {
                bool changeTrackingEnabled = entity.ChangeTracker.ChangeTrackingEnabled;
                try
                {
                    entity.MarkAsUnchanged();
                }
                finally
                {
                    entity.ChangeTracker.ChangeTrackingEnabled = changeTrackingEnabled;
                }
                this.StoreReferenceKeyValues(entity);
            }
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public ObjectSet<UsrCredit> UsrCredits
        {
            get { return _usrCredits  ?? (_usrCredits = CreateObjectSet<UsrCredit>("UsrCredits")); }
        }
        private ObjectSet<UsrCredit> _usrCredits;
    
        public ObjectSet<Bulk_Request> Bulk_Request
        {
            get { return _bulk_Request  ?? (_bulk_Request = CreateObjectSet<Bulk_Request>("Bulk_Request")); }
        }
        private ObjectSet<Bulk_Request> _bulk_Request;
    
        public ObjectSet<Tbl_Customers> Tbl_Customers
        {
            get { return _tbl_Customers  ?? (_tbl_Customers = CreateObjectSet<Tbl_Customers>("Tbl_Customers")); }
        }
        private ObjectSet<Tbl_Customers> _tbl_Customers;
    
        public ObjectSet<Tbl_LineNumber> Tbl_LineNumber
        {
            get { return _tbl_LineNumber  ?? (_tbl_LineNumber = CreateObjectSet<Tbl_LineNumber>("Tbl_LineNumber")); }
        }
        private ObjectSet<Tbl_LineNumber> _tbl_LineNumber;
    
        public ObjectSet<Tbl_UserAccountRole> Tbl_UserAccountRole
        {
            get { return _tbl_UserAccountRole  ?? (_tbl_UserAccountRole = CreateObjectSet<Tbl_UserAccountRole>("Tbl_UserAccountRole")); }
        }
        private ObjectSet<Tbl_UserAccountRole> _tbl_UserAccountRole;
    
        public ObjectSet<UserInfo> UserInfoes
        {
            get { return _userInfoes  ?? (_userInfoes = CreateObjectSet<UserInfo>("UserInfoes")); }
        }
        private ObjectSet<UserInfo> _userInfoes;
    
        public ObjectSet<OperatorTarrifRate> OperatorTarrifRates
        {
            get { return _operatorTarrifRates  ?? (_operatorTarrifRates = CreateObjectSet<OperatorTarrifRate>("OperatorTarrifRates")); }
        }
        private ObjectSet<OperatorTarrifRate> _operatorTarrifRates;
    
        public ObjectSet<Tbl_RecieveSms> Tbl_RecieveSms
        {
            get { return _tbl_RecieveSms  ?? (_tbl_RecieveSms = CreateObjectSet<Tbl_RecieveSms>("Tbl_RecieveSms")); }
        }
        private ObjectSet<Tbl_RecieveSms> _tbl_RecieveSms;
    
        public ObjectSet<tbl_Extensible> tbl_Extensible
        {
            get { return _tbl_Extensible  ?? (_tbl_Extensible = CreateObjectSet<tbl_Extensible>("tbl_Extensible")); }
        }
        private ObjectSet<tbl_Extensible> _tbl_Extensible;
    
        public ObjectSet<Tbl_UserAccount> Tbl_UserAccount
        {
            get { return _tbl_UserAccount  ?? (_tbl_UserAccount = CreateObjectSet<Tbl_UserAccount>("Tbl_UserAccount")); }
        }
        private ObjectSet<Tbl_UserAccount> _tbl_UserAccount;
    
        public ObjectSet<Bulk> Bulks
        {
            get { return _bulks  ?? (_bulks = CreateObjectSet<Bulk>("Bulks")); }
        }
        private ObjectSet<Bulk> _bulks;
    
        public ObjectSet<View_Tbl_SentSMS> View_Tbl_SentSMS
        {
            get { return _view_Tbl_SentSMS  ?? (_view_Tbl_SentSMS = CreateObjectSet<View_Tbl_SentSMS>("View_Tbl_SentSMS")); }
        }
        private ObjectSet<View_Tbl_SentSMS> _view_Tbl_SentSMS;
    
        public ObjectSet<Tbl_SentSMS> Tbl_SentSMS
        {
            get { return _tbl_SentSMS  ?? (_tbl_SentSMS = CreateObjectSet<Tbl_SentSMS>("Tbl_SentSMS")); }
        }
        private ObjectSet<Tbl_SentSMS> _tbl_SentSMS;
    
        public ObjectSet<Tbl_Payment> Tbl_Payment
        {
            get { return _tbl_Payment  ?? (_tbl_Payment = CreateObjectSet<Tbl_Payment>("Tbl_Payment")); }
        }
        private ObjectSet<Tbl_Payment> _tbl_Payment;

        #endregion

        #region Function Imports
        public virtual ObjectResult<Tbl_RecieveSms> SpTbl_RecieveUnreadedSms_Select(string rcvSmsTo, string dateFrom, string dateTo, string timeFrom, string timeTo, string usrId, string today)
        {
    
            ObjectParameter rcvSmsToParameter;
    
            if (rcvSmsTo != null)
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", rcvSmsTo);
            }
            else
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", typeof(string));
            }
    
            ObjectParameter dateFromParameter;
    
            if (dateFrom != null)
            {
                dateFromParameter = new ObjectParameter("DateFrom", dateFrom);
            }
            else
            {
                dateFromParameter = new ObjectParameter("DateFrom", typeof(string));
            }
    
            ObjectParameter dateToParameter;
    
            if (dateTo != null)
            {
                dateToParameter = new ObjectParameter("DateTo", dateTo);
            }
            else
            {
                dateToParameter = new ObjectParameter("DateTo", typeof(string));
            }
    
            ObjectParameter timeFromParameter;
    
            if (timeFrom != null)
            {
                timeFromParameter = new ObjectParameter("TimeFrom", timeFrom);
            }
            else
            {
                timeFromParameter = new ObjectParameter("TimeFrom", typeof(string));
            }
    
            ObjectParameter timeToParameter;
    
            if (timeTo != null)
            {
                timeToParameter = new ObjectParameter("TimeTo", timeTo);
            }
            else
            {
                timeToParameter = new ObjectParameter("TimeTo", typeof(string));
            }
    
            ObjectParameter usrIdParameter;
    
            if (usrId != null)
            {
                usrIdParameter = new ObjectParameter("UsrId", usrId);
            }
            else
            {
                usrIdParameter = new ObjectParameter("UsrId", typeof(string));
            }
    
            ObjectParameter todayParameter;
    
            if (today != null)
            {
                todayParameter = new ObjectParameter("Today", today);
            }
            else
            {
                todayParameter = new ObjectParameter("Today", typeof(string));
            }
            return base.ExecuteFunction<Tbl_RecieveSms>("SpTbl_RecieveUnreadedSms_Select", rcvSmsToParameter, dateFromParameter, dateToParameter, timeFromParameter, timeToParameter, usrIdParameter, todayParameter);
        }
        public virtual ObjectResult<Tbl_RecieveSms> GetRecieveSMS(string rcvSmsTo, string dateFrom, string dateTo, string timeFrom, string timeTo, string today)
        {
    
            ObjectParameter rcvSmsToParameter;
    
            if (rcvSmsTo != null)
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", rcvSmsTo);
            }
            else
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", typeof(string));
            }
    
            ObjectParameter dateFromParameter;
    
            if (dateFrom != null)
            {
                dateFromParameter = new ObjectParameter("DateFrom", dateFrom);
            }
            else
            {
                dateFromParameter = new ObjectParameter("DateFrom", typeof(string));
            }
    
            ObjectParameter dateToParameter;
    
            if (dateTo != null)
            {
                dateToParameter = new ObjectParameter("DateTo", dateTo);
            }
            else
            {
                dateToParameter = new ObjectParameter("DateTo", typeof(string));
            }
    
            ObjectParameter timeFromParameter;
    
            if (timeFrom != null)
            {
                timeFromParameter = new ObjectParameter("TimeFrom", timeFrom);
            }
            else
            {
                timeFromParameter = new ObjectParameter("TimeFrom", typeof(string));
            }
    
            ObjectParameter timeToParameter;
    
            if (timeTo != null)
            {
                timeToParameter = new ObjectParameter("TimeTo", timeTo);
            }
            else
            {
                timeToParameter = new ObjectParameter("TimeTo", typeof(string));
            }
    
            ObjectParameter todayParameter;
    
            if (today != null)
            {
                todayParameter = new ObjectParameter("Today", today);
            }
            else
            {
                todayParameter = new ObjectParameter("Today", typeof(string));
            }
            return base.ExecuteFunction<Tbl_RecieveSms>("GetRecieveSMS", rcvSmsToParameter, dateFromParameter, dateToParameter, timeFromParameter, timeToParameter, todayParameter);
        }
        public virtual ObjectResult<Nullable<int>> SpTbl_UsrCredit_SelectTotalCredit(string usrId, string today)
        {
    
            ObjectParameter usrIdParameter;
    
            if (usrId != null)
            {
                usrIdParameter = new ObjectParameter("UsrId", usrId);
            }
            else
            {
                usrIdParameter = new ObjectParameter("UsrId", typeof(string));
            }
    
            ObjectParameter todayParameter;
    
            if (today != null)
            {
                todayParameter = new ObjectParameter("Today", today);
            }
            else
            {
                todayParameter = new ObjectParameter("Today", typeof(string));
            }
            return base.ExecuteFunction<Nullable<int>>("SpTbl_UsrCredit_SelectTotalCredit", usrIdParameter, todayParameter);
        }
        public virtual ObjectResult<Nullable<int>> SpTbl_OnlineUsrCredit_Insert(string iUsrId, Nullable<int> payTypeCode, Nullable<int> paymentAmount, string paymentDate, Nullable<bool> payFlag, Nullable<int> iSMSFaPrice, Nullable<int> iSMSEnPrice, Nullable<int> iRcvSmsPrice, Nullable<System.DateTime> payDate, string transactionNumber, Nullable<int> bankId, string invoiceNumber, string description)
        {
    
            ObjectParameter iUsrIdParameter;
    
            if (iUsrId != null)
            {
                iUsrIdParameter = new ObjectParameter("IUsrId", iUsrId);
            }
            else
            {
                iUsrIdParameter = new ObjectParameter("IUsrId", typeof(string));
            }
    
            ObjectParameter payTypeCodeParameter;
    
            if (payTypeCode.HasValue)
            {
                payTypeCodeParameter = new ObjectParameter("PayTypeCode", payTypeCode);
            }
            else
            {
                payTypeCodeParameter = new ObjectParameter("PayTypeCode", typeof(int));
            }
    
            ObjectParameter paymentAmountParameter;
    
            if (paymentAmount.HasValue)
            {
                paymentAmountParameter = new ObjectParameter("PaymentAmount", paymentAmount);
            }
            else
            {
                paymentAmountParameter = new ObjectParameter("PaymentAmount", typeof(int));
            }
    
            ObjectParameter paymentDateParameter;
    
            if (paymentDate != null)
            {
                paymentDateParameter = new ObjectParameter("PaymentDate", paymentDate);
            }
            else
            {
                paymentDateParameter = new ObjectParameter("PaymentDate", typeof(string));
            }
    
            ObjectParameter payFlagParameter;
    
            if (payFlag.HasValue)
            {
                payFlagParameter = new ObjectParameter("PayFlag", payFlag);
            }
            else
            {
                payFlagParameter = new ObjectParameter("PayFlag", typeof(bool));
            }
    
            ObjectParameter iSMSFaPriceParameter;
    
            if (iSMSFaPrice.HasValue)
            {
                iSMSFaPriceParameter = new ObjectParameter("ISMSFaPrice", iSMSFaPrice);
            }
            else
            {
                iSMSFaPriceParameter = new ObjectParameter("ISMSFaPrice", typeof(int));
            }
    
            ObjectParameter iSMSEnPriceParameter;
    
            if (iSMSEnPrice.HasValue)
            {
                iSMSEnPriceParameter = new ObjectParameter("ISMSEnPrice", iSMSEnPrice);
            }
            else
            {
                iSMSEnPriceParameter = new ObjectParameter("ISMSEnPrice", typeof(int));
            }
    
            ObjectParameter iRcvSmsPriceParameter;
    
            if (iRcvSmsPrice.HasValue)
            {
                iRcvSmsPriceParameter = new ObjectParameter("IRcvSmsPrice", iRcvSmsPrice);
            }
            else
            {
                iRcvSmsPriceParameter = new ObjectParameter("IRcvSmsPrice", typeof(int));
            }
    
            ObjectParameter payDateParameter;
    
            if (payDate.HasValue)
            {
                payDateParameter = new ObjectParameter("PayDate", payDate);
            }
            else
            {
                payDateParameter = new ObjectParameter("PayDate", typeof(System.DateTime));
            }
    
            ObjectParameter transactionNumberParameter;
    
            if (transactionNumber != null)
            {
                transactionNumberParameter = new ObjectParameter("TransactionNumber", transactionNumber);
            }
            else
            {
                transactionNumberParameter = new ObjectParameter("TransactionNumber", typeof(string));
            }
    
            ObjectParameter bankIdParameter;
    
            if (bankId.HasValue)
            {
                bankIdParameter = new ObjectParameter("BankId", bankId);
            }
            else
            {
                bankIdParameter = new ObjectParameter("BankId", typeof(int));
            }
    
            ObjectParameter invoiceNumberParameter;
    
            if (invoiceNumber != null)
            {
                invoiceNumberParameter = new ObjectParameter("InvoiceNumber", invoiceNumber);
            }
            else
            {
                invoiceNumberParameter = new ObjectParameter("InvoiceNumber", typeof(string));
            }
    
            ObjectParameter descriptionParameter;
    
            if (description != null)
            {
                descriptionParameter = new ObjectParameter("Description", description);
            }
            else
            {
                descriptionParameter = new ObjectParameter("Description", typeof(string));
            }
            return base.ExecuteFunction<Nullable<int>>("SpTbl_OnlineUsrCredit_Insert", iUsrIdParameter, payTypeCodeParameter, paymentAmountParameter, paymentDateParameter, payFlagParameter, iSMSFaPriceParameter, iSMSEnPriceParameter, iRcvSmsPriceParameter, payDateParameter, transactionNumberParameter, bankIdParameter, invoiceNumberParameter, descriptionParameter);
        }
        public virtual ObjectResult<Tbl_RecieveSms> SpTbl_RecieveSms_SelectFromId(string rcvSmsTo, Nullable<int> smsId)
        {
    
            ObjectParameter rcvSmsToParameter;
    
            if (rcvSmsTo != null)
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", rcvSmsTo);
            }
            else
            {
                rcvSmsToParameter = new ObjectParameter("RcvSmsTo", typeof(string));
            }
    
            ObjectParameter smsIdParameter;
    
            if (smsId.HasValue)
            {
                smsIdParameter = new ObjectParameter("SmsId", smsId);
            }
            else
            {
                smsIdParameter = new ObjectParameter("SmsId", typeof(int));
            }
            return base.ExecuteFunction<Tbl_RecieveSms>("SpTbl_RecieveSms_SelectFromId", rcvSmsToParameter, smsIdParameter);
        }
        public virtual ObjectResult<Nullable<int>> SpTbl_Usrcredit_UpdateCredit(string usrId, Nullable<int> faSmsCount, Nullable<int> enSmsCount, string today, Nullable<double> rate, Nullable<byte> trActionType)
        {
    
            ObjectParameter usrIdParameter;
    
            if (usrId != null)
            {
                usrIdParameter = new ObjectParameter("UsrId", usrId);
            }
            else
            {
                usrIdParameter = new ObjectParameter("UsrId", typeof(string));
            }
    
            ObjectParameter faSmsCountParameter;
    
            if (faSmsCount.HasValue)
            {
                faSmsCountParameter = new ObjectParameter("FaSmsCount", faSmsCount);
            }
            else
            {
                faSmsCountParameter = new ObjectParameter("FaSmsCount", typeof(int));
            }
    
            ObjectParameter enSmsCountParameter;
    
            if (enSmsCount.HasValue)
            {
                enSmsCountParameter = new ObjectParameter("EnSmsCount", enSmsCount);
            }
            else
            {
                enSmsCountParameter = new ObjectParameter("EnSmsCount", typeof(int));
            }
    
            ObjectParameter todayParameter;
    
            if (today != null)
            {
                todayParameter = new ObjectParameter("Today", today);
            }
            else
            {
                todayParameter = new ObjectParameter("Today", typeof(string));
            }
    
            ObjectParameter rateParameter;
    
            if (rate.HasValue)
            {
                rateParameter = new ObjectParameter("Rate", rate);
            }
            else
            {
                rateParameter = new ObjectParameter("Rate", typeof(double));
            }
    
            ObjectParameter trActionTypeParameter;
    
            if (trActionType.HasValue)
            {
                trActionTypeParameter = new ObjectParameter("TrActionType", trActionType);
            }
            else
            {
                trActionTypeParameter = new ObjectParameter("TrActionType", typeof(byte));
            }
            return base.ExecuteFunction<Nullable<int>>("SpTbl_Usrcredit_UpdateCredit", usrIdParameter, faSmsCountParameter, enSmsCountParameter, todayParameter, rateParameter, trActionTypeParameter);
        }

        #endregion

    }
}
