//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class ReservedLineNumbers
    {
        public string LineNumber { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> Price { get; set; }
        public int Id { get; set; }
    }
    
}
