//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tbl_UserAccount))]
    [KnownType(typeof(Bulk))]
    public partial class Tbl_LineNumber: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ILineNumberCode
        {
            get { return _iLineNumberCode; }
            set
            {
                if (_iLineNumberCode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ILineNumberCode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iLineNumberCode = value;
                    OnPropertyChanged("ILineNumberCode");
                }
            }
        }
        private int _iLineNumberCode;
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    ChangeTracker.RecordOriginalValue("IUsrId", _iUsrId);
                    if (!IsDeserializing)
                    {
                        if (Tbl_UserAccount != null && Tbl_UserAccount.IUsrId != value)
                        {
                            Tbl_UserAccount = null;
                        }
                    }
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public string ILineNumber
        {
            get { return _iLineNumber; }
            set
            {
                if (_iLineNumber != value)
                {
                    _iLineNumber = value;
                    OnPropertyChanged("ILineNumber");
                }
            }
        }
        private string _iLineNumber;
    
        [DataMember]
        public string ILineModuleNumber
        {
            get { return _iLineModuleNumber; }
            set
            {
                if (_iLineModuleNumber != value)
                {
                    _iLineModuleNumber = value;
                    OnPropertyChanged("ILineModuleNumber");
                }
            }
        }
        private string _iLineModuleNumber;
    
        [DataMember]
        public string ILineServiceType
        {
            get { return _iLineServiceType; }
            set
            {
                if (_iLineServiceType != value)
                {
                    _iLineServiceType = value;
                    OnPropertyChanged("ILineServiceType");
                }
            }
        }
        private string _iLineServiceType;
    
        [DataMember]
        public string ILineKeyWord
        {
            get { return _iLineKeyWord; }
            set
            {
                if (_iLineKeyWord != value)
                {
                    _iLineKeyWord = value;
                    OnPropertyChanged("ILineKeyWord");
                }
            }
        }
        private string _iLineKeyWord;
    
        [DataMember]
        public string ILineStatuse
        {
            get { return _iLineStatuse; }
            set
            {
                if (_iLineStatuse != value)
                {
                    _iLineStatuse = value;
                    OnPropertyChanged("ILineStatuse");
                }
            }
        }
        private string _iLineStatuse;
    
        [DataMember]
        public string ILineLastModify
        {
            get { return _iLineLastModify; }
            set
            {
                if (_iLineLastModify != value)
                {
                    _iLineLastModify = value;
                    OnPropertyChanged("ILineLastModify");
                }
            }
        }
        private string _iLineLastModify;
    
        [DataMember]
        public string ILineDuration
        {
            get { return _iLineDuration; }
            set
            {
                if (_iLineDuration != value)
                {
                    _iLineDuration = value;
                    OnPropertyChanged("ILineDuration");
                }
            }
        }
        private string _iLineDuration;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Tbl_UserAccount Tbl_UserAccount
        {
            get { return _tbl_UserAccount; }
            set
            {
                if (!ReferenceEquals(_tbl_UserAccount, value))
                {
                    var previousValue = _tbl_UserAccount;
                    _tbl_UserAccount = value;
                    FixupTbl_UserAccount(previousValue);
                    OnNavigationPropertyChanged("Tbl_UserAccount");
                }
            }
        }
        private Tbl_UserAccount _tbl_UserAccount;
    
        [DataMember]
        public TrackableCollection<Bulk> Bulks
        {
            get
            {
                if (_bulks == null)
                {
                    _bulks = new TrackableCollection<Bulk>();
                    _bulks.CollectionChanged += FixupBulks;
                }
                return _bulks;
            }
            set
            {
                if (!ReferenceEquals(_bulks, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bulks != null)
                    {
                        _bulks.CollectionChanged -= FixupBulks;
                    }
                    _bulks = value;
                    if (_bulks != null)
                    {
                        _bulks.CollectionChanged += FixupBulks;
                    }
                    OnNavigationPropertyChanged("Bulks");
                }
            }
        }
        private TrackableCollection<Bulk> _bulks;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_UserAccount = null;
            Bulks.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_UserAccount(Tbl_UserAccount previousValue, bool skipKeys = false)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Tbl_LineNumber.Contains(this))
            {
                previousValue.Tbl_LineNumber.Remove(this);
            }
    
            if (Tbl_UserAccount != null)
            {
                if (!Tbl_UserAccount.Tbl_LineNumber.Contains(this))
                {
                    Tbl_UserAccount.Tbl_LineNumber.Add(this);
                }
    
                IUsrId = Tbl_UserAccount.IUsrId;
            }
            else if (!skipKeys)
            {
                IUsrId = null;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_UserAccount")
                    && (ChangeTracker.OriginalValues["Tbl_UserAccount"] == Tbl_UserAccount))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_UserAccount");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_UserAccount", previousValue);
                }
                if (Tbl_UserAccount != null && !Tbl_UserAccount.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_UserAccount.StartTracking();
                }
            }
        }
    
        private void FixupBulks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Bulk item in e.NewItems)
                {
                    item.Tbl_LineNumber = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Bulks", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Bulk item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tbl_LineNumber, this))
                    {
                        item.Tbl_LineNumber = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Bulks", item);
                    }
                }
            }
        }

        #endregion

    }
}
