//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tbl_Customers))]
    [KnownType(typeof(Tbl_LineNumber))]
    [KnownType(typeof(Tbl_UserAccountRole))]
    [KnownType(typeof(Bulk))]
    public partial class Tbl_UserAccount: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int IUsrAccCode
        {
            get { return _iUsrAccCode; }
            set
            {
                if (_iUsrAccCode != value)
                {
                    _iUsrAccCode = value;
                    OnPropertyChanged("IUsrAccCode");
                }
            }
        }
        private int _iUsrAccCode;
    
        [DataMember]
        public Nullable<int> IUserParentID
        {
            get { return _iUserParentID; }
            set
            {
                if (_iUserParentID != value)
                {
                    _iUserParentID = value;
                    OnPropertyChanged("IUserParentID");
                }
            }
        }
        private Nullable<int> _iUserParentID;
    
        [DataMember]
        public string IUsrManagerId
        {
            get { return _iUsrManagerId; }
            set
            {
                if (_iUsrManagerId != value)
                {
                    _iUsrManagerId = value;
                    OnPropertyChanged("IUsrManagerId");
                }
            }
        }
        private string _iUsrManagerId;
    
        [DataMember]
        public int IUsrCCode
        {
            get { return _iUsrCCode; }
            set
            {
                if (_iUsrCCode != value)
                {
                    ChangeTracker.RecordOriginalValue("IUsrCCode", _iUsrCCode);
                    if (!IsDeserializing)
                    {
                        if (Tbl_Customers != null && Tbl_Customers.ICCode != value)
                        {
                            Tbl_Customers = null;
                        }
                    }
                    _iUsrCCode = value;
                    OnPropertyChanged("IUsrCCode");
                }
            }
        }
        private int _iUsrCCode;
    
        [DataMember]
        public int AscRoleCode
        {
            get { return _ascRoleCode; }
            set
            {
                if (_ascRoleCode != value)
                {
                    ChangeTracker.RecordOriginalValue("AscRoleCode", _ascRoleCode);
                    if (!IsDeserializing)
                    {
                        if (Tbl_UserAccountRole != null && Tbl_UserAccountRole.AcsRoleCode != value)
                        {
                            Tbl_UserAccountRole = null;
                        }
                    }
                    _ascRoleCode = value;
                    OnPropertyChanged("AscRoleCode");
                }
            }
        }
        private int _ascRoleCode;
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IUsrId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public string IUsrPaswrd
        {
            get { return _iUsrPaswrd; }
            set
            {
                if (_iUsrPaswrd != value)
                {
                    _iUsrPaswrd = value;
                    OnPropertyChanged("IUsrPaswrd");
                }
            }
        }
        private string _iUsrPaswrd;
    
        [DataMember]
        public Nullable<bool> IUsrActive
        {
            get { return _iUsrActive; }
            set
            {
                if (_iUsrActive != value)
                {
                    _iUsrActive = value;
                    OnPropertyChanged("IUsrActive");
                }
            }
        }
        private Nullable<bool> _iUsrActive;
    
        [DataMember]
        public Nullable<bool> IUsrSpesial
        {
            get { return _iUsrSpesial; }
            set
            {
                if (_iUsrSpesial != value)
                {
                    _iUsrSpesial = value;
                    OnPropertyChanged("IUsrSpesial");
                }
            }
        }
        private Nullable<bool> _iUsrSpesial;
    
        [DataMember]
        public Nullable<bool> IUsrISAdmin
        {
            get { return _iUsrISAdmin; }
            set
            {
                if (_iUsrISAdmin != value)
                {
                    _iUsrISAdmin = value;
                    OnPropertyChanged("IUsrISAdmin");
                }
            }
        }
        private Nullable<bool> _iUsrISAdmin;
    
        [DataMember]
        public string IUsrIName
        {
            get { return _iUsrIName; }
            set
            {
                if (_iUsrIName != value)
                {
                    _iUsrIName = value;
                    OnPropertyChanged("IUsrIName");
                }
            }
        }
        private string _iUsrIName;
    
        [DataMember]
        public string IUsrAccCreatDate
        {
            get { return _iUsrAccCreatDate; }
            set
            {
                if (_iUsrAccCreatDate != value)
                {
                    _iUsrAccCreatDate = value;
                    OnPropertyChanged("IUsrAccCreatDate");
                }
            }
        }
        private string _iUsrAccCreatDate;
    
        [DataMember]
        public string IUsrAccExpireDate
        {
            get { return _iUsrAccExpireDate; }
            set
            {
                if (_iUsrAccExpireDate != value)
                {
                    _iUsrAccExpireDate = value;
                    OnPropertyChanged("IUsrAccExpireDate");
                }
            }
        }
        private string _iUsrAccExpireDate;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Tbl_Customers Tbl_Customers
        {
            get { return _tbl_Customers; }
            set
            {
                if (!ReferenceEquals(_tbl_Customers, value))
                {
                    var previousValue = _tbl_Customers;
                    _tbl_Customers = value;
                    FixupTbl_Customers(previousValue);
                    OnNavigationPropertyChanged("Tbl_Customers");
                }
            }
        }
        private Tbl_Customers _tbl_Customers;
    
        [DataMember]
        public TrackableCollection<Tbl_LineNumber> Tbl_LineNumber
        {
            get
            {
                if (_tbl_LineNumber == null)
                {
                    _tbl_LineNumber = new TrackableCollection<Tbl_LineNumber>();
                    _tbl_LineNumber.CollectionChanged += FixupTbl_LineNumber;
                }
                return _tbl_LineNumber;
            }
            set
            {
                if (!ReferenceEquals(_tbl_LineNumber, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tbl_LineNumber != null)
                    {
                        _tbl_LineNumber.CollectionChanged -= FixupTbl_LineNumber;
                    }
                    _tbl_LineNumber = value;
                    if (_tbl_LineNumber != null)
                    {
                        _tbl_LineNumber.CollectionChanged += FixupTbl_LineNumber;
                    }
                    OnNavigationPropertyChanged("Tbl_LineNumber");
                }
            }
        }
        private TrackableCollection<Tbl_LineNumber> _tbl_LineNumber;
    
        [DataMember]
        public Tbl_UserAccountRole Tbl_UserAccountRole
        {
            get { return _tbl_UserAccountRole; }
            set
            {
                if (!ReferenceEquals(_tbl_UserAccountRole, value))
                {
                    var previousValue = _tbl_UserAccountRole;
                    _tbl_UserAccountRole = value;
                    FixupTbl_UserAccountRole(previousValue);
                    OnNavigationPropertyChanged("Tbl_UserAccountRole");
                }
            }
        }
        private Tbl_UserAccountRole _tbl_UserAccountRole;
    
        [DataMember]
        public TrackableCollection<Bulk> Bulks
        {
            get
            {
                if (_bulks == null)
                {
                    _bulks = new TrackableCollection<Bulk>();
                    _bulks.CollectionChanged += FixupBulks;
                }
                return _bulks;
            }
            set
            {
                if (!ReferenceEquals(_bulks, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_bulks != null)
                    {
                        _bulks.CollectionChanged -= FixupBulks;
                    }
                    _bulks = value;
                    if (_bulks != null)
                    {
                        _bulks.CollectionChanged += FixupBulks;
                    }
                    OnNavigationPropertyChanged("Bulks");
                }
            }
        }
        private TrackableCollection<Bulk> _bulks;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_Customers = null;
            Tbl_LineNumber.Clear();
            Tbl_UserAccountRole = null;
            Bulks.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_Customers(Tbl_Customers previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Tbl_UserAccount.Contains(this))
            {
                previousValue.Tbl_UserAccount.Remove(this);
            }
    
            if (Tbl_Customers != null)
            {
                if (!Tbl_Customers.Tbl_UserAccount.Contains(this))
                {
                    Tbl_Customers.Tbl_UserAccount.Add(this);
                }
    
                IUsrCCode = Tbl_Customers.ICCode;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_Customers")
                    && (ChangeTracker.OriginalValues["Tbl_Customers"] == Tbl_Customers))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_Customers");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_Customers", previousValue);
                }
                if (Tbl_Customers != null && !Tbl_Customers.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_Customers.StartTracking();
                }
            }
        }
    
        private void FixupTbl_UserAccountRole(Tbl_UserAccountRole previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && previousValue.Tbl_UserAccount.Contains(this))
            {
                previousValue.Tbl_UserAccount.Remove(this);
            }
    
            if (Tbl_UserAccountRole != null)
            {
                if (!Tbl_UserAccountRole.Tbl_UserAccount.Contains(this))
                {
                    Tbl_UserAccountRole.Tbl_UserAccount.Add(this);
                }
    
                AscRoleCode = Tbl_UserAccountRole.AcsRoleCode;
            }
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_UserAccountRole")
                    && (ChangeTracker.OriginalValues["Tbl_UserAccountRole"] == Tbl_UserAccountRole))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_UserAccountRole");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_UserAccountRole", previousValue);
                }
                if (Tbl_UserAccountRole != null && !Tbl_UserAccountRole.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_UserAccountRole.StartTracking();
                }
            }
        }
    
        private void FixupTbl_LineNumber(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Tbl_LineNumber item in e.NewItems)
                {
                    item.Tbl_UserAccount = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Tbl_LineNumber", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Tbl_LineNumber item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tbl_UserAccount, this))
                    {
                        item.Tbl_UserAccount = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Tbl_LineNumber", item);
                    }
                }
            }
        }
    
        private void FixupBulks(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Bulk item in e.NewItems)
                {
                    item.Tbl_UserAccount = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Bulks", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Bulk item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tbl_UserAccount, this))
                    {
                        item.Tbl_UserAccount = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Bulks", item);
                    }
                }
            }
        }

        #endregion

    }
}
