//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class Tbl_UsrCredit
    {
        public int PaymentId { get; set; }
        public string IUsrId { get; set; }
        public Nullable<int> ICreditAmount { get; set; }
        public Nullable<int> ISMSFaPrice { get; set; }
        public Nullable<int> ISMSEnPrice { get; set; }
        public Nullable<int> IRcvSmsPrice { get; set; }
    }
    
}
