//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tbl_UserAccount))]
    public partial class Tbl_Customers: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int ICCode
        {
            get { return _iCCode; }
            set
            {
                if (_iCCode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ICCode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iCCode = value;
                    OnPropertyChanged("ICCode");
                }
            }
        }
        private int _iCCode;
    
        [DataMember]
        public Nullable<int> ICParentID
        {
            get { return _iCParentID; }
            set
            {
                if (_iCParentID != value)
                {
                    _iCParentID = value;
                    OnPropertyChanged("ICParentID");
                }
            }
        }
        private Nullable<int> _iCParentID;
    
        [DataMember]
        public Nullable<int> IProviencyCode
        {
            get { return _iProviencyCode; }
            set
            {
                if (_iProviencyCode != value)
                {
                    _iProviencyCode = value;
                    OnPropertyChanged("IProviencyCode");
                }
            }
        }
        private Nullable<int> _iProviencyCode;
    
        [DataMember]
        public Nullable<int> ICityCode
        {
            get { return _iCityCode; }
            set
            {
                if (_iCityCode != value)
                {
                    _iCityCode = value;
                    OnPropertyChanged("ICityCode");
                }
            }
        }
        private Nullable<int> _iCityCode;
    
        [DataMember]
        public Nullable<int> IActTypeCode
        {
            get { return _iActTypeCode; }
            set
            {
                if (_iActTypeCode != value)
                {
                    _iActTypeCode = value;
                    OnPropertyChanged("IActTypeCode");
                }
            }
        }
        private Nullable<int> _iActTypeCode;
    
        [DataMember]
        public string ICName
        {
            get { return _iCName; }
            set
            {
                if (_iCName != value)
                {
                    _iCName = value;
                    OnPropertyChanged("ICName");
                }
            }
        }
        private string _iCName;
    
        [DataMember]
        public string ICLName
        {
            get { return _iCLName; }
            set
            {
                if (_iCLName != value)
                {
                    _iCLName = value;
                    OnPropertyChanged("ICLName");
                }
            }
        }
        private string _iCLName;
    
        [DataMember]
        public string ICTel
        {
            get { return _iCTel; }
            set
            {
                if (_iCTel != value)
                {
                    _iCTel = value;
                    OnPropertyChanged("ICTel");
                }
            }
        }
        private string _iCTel;
    
        [DataMember]
        public string ICMobile
        {
            get { return _iCMobile; }
            set
            {
                if (_iCMobile != value)
                {
                    _iCMobile = value;
                    OnPropertyChanged("ICMobile");
                }
            }
        }
        private string _iCMobile;
    
        [DataMember]
        public string ICFax
        {
            get { return _iCFax; }
            set
            {
                if (_iCFax != value)
                {
                    _iCFax = value;
                    OnPropertyChanged("ICFax");
                }
            }
        }
        private string _iCFax;
    
        [DataMember]
        public string ICEmail
        {
            get { return _iCEmail; }
            set
            {
                if (_iCEmail != value)
                {
                    _iCEmail = value;
                    OnPropertyChanged("ICEmail");
                }
            }
        }
        private string _iCEmail;
    
        [DataMember]
        public string ICWebSite
        {
            get { return _iCWebSite; }
            set
            {
                if (_iCWebSite != value)
                {
                    _iCWebSite = value;
                    OnPropertyChanged("ICWebSite");
                }
            }
        }
        private string _iCWebSite;
    
        [DataMember]
        public string ICPrsAdrs
        {
            get { return _iCPrsAdrs; }
            set
            {
                if (_iCPrsAdrs != value)
                {
                    _iCPrsAdrs = value;
                    OnPropertyChanged("ICPrsAdrs");
                }
            }
        }
        private string _iCPrsAdrs;
    
        [DataMember]
        public string ICZipeCode
        {
            get { return _iCZipeCode; }
            set
            {
                if (_iCZipeCode != value)
                {
                    _iCZipeCode = value;
                    OnPropertyChanged("ICZipeCode");
                }
            }
        }
        private string _iCZipeCode;
    
        [DataMember]
        public string ICCoName
        {
            get { return _iCCoName; }
            set
            {
                if (_iCCoName != value)
                {
                    _iCCoName = value;
                    OnPropertyChanged("ICCoName");
                }
            }
        }
        private string _iCCoName;
    
        [DataMember]
        public Nullable<bool> ICCoType
        {
            get { return _iCCoType; }
            set
            {
                if (_iCCoType != value)
                {
                    _iCCoType = value;
                    OnPropertyChanged("ICCoType");
                }
            }
        }
        private Nullable<bool> _iCCoType;
    
        [DataMember]
        public string ICCoActivity
        {
            get { return _iCCoActivity; }
            set
            {
                if (_iCCoActivity != value)
                {
                    _iCCoActivity = value;
                    OnPropertyChanged("ICCoActivity");
                }
            }
        }
        private string _iCCoActivity;
    
        [DataMember]
        public string ICDescrtiption
        {
            get { return _iCDescrtiption; }
            set
            {
                if (_iCDescrtiption != value)
                {
                    _iCDescrtiption = value;
                    OnPropertyChanged("ICDescrtiption");
                }
            }
        }
        private string _iCDescrtiption;
    
        [DataMember]
        public string ICPrsNumber
        {
            get { return _iCPrsNumber; }
            set
            {
                if (_iCPrsNumber != value)
                {
                    _iCPrsNumber = value;
                    OnPropertyChanged("ICPrsNumber");
                }
            }
        }
        private string _iCPrsNumber;
    
        [DataMember]
        public string ICMeliCartPic
        {
            get { return _iCMeliCartPic; }
            set
            {
                if (_iCMeliCartPic != value)
                {
                    _iCMeliCartPic = value;
                    OnPropertyChanged("ICMeliCartPic");
                }
            }
        }
        private string _iCMeliCartPic;
    
        [DataMember]
        public string ICPrsNumberPic
        {
            get { return _iCPrsNumberPic; }
            set
            {
                if (_iCPrsNumberPic != value)
                {
                    _iCPrsNumberPic = value;
                    OnPropertyChanged("ICPrsNumberPic");
                }
            }
        }
        private string _iCPrsNumberPic;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Tbl_UserAccount> Tbl_UserAccount
        {
            get
            {
                if (_tbl_UserAccount == null)
                {
                    _tbl_UserAccount = new TrackableCollection<Tbl_UserAccount>();
                    _tbl_UserAccount.CollectionChanged += FixupTbl_UserAccount;
                }
                return _tbl_UserAccount;
            }
            set
            {
                if (!ReferenceEquals(_tbl_UserAccount, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tbl_UserAccount != null)
                    {
                        _tbl_UserAccount.CollectionChanged -= FixupTbl_UserAccount;
                    }
                    _tbl_UserAccount = value;
                    if (_tbl_UserAccount != null)
                    {
                        _tbl_UserAccount.CollectionChanged += FixupTbl_UserAccount;
                    }
                    OnNavigationPropertyChanged("Tbl_UserAccount");
                }
            }
        }
        private TrackableCollection<Tbl_UserAccount> _tbl_UserAccount;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_UserAccount.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_UserAccount(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Tbl_UserAccount item in e.NewItems)
                {
                    item.Tbl_Customers = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Tbl_UserAccount", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Tbl_UserAccount item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tbl_Customers, this))
                    {
                        item.Tbl_Customers = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Tbl_UserAccount", item);
                    }
                }
            }
        }

        #endregion

    }
}
