//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    public partial class tbl_Extensible: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IUsrId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public string ServerURL
        {
            get { return _serverURL; }
            set
            {
                if (_serverURL != value)
                {
                    _serverURL = value;
                    OnPropertyChanged("ServerURL");
                }
            }
        }
        private string _serverURL;
    
        [DataMember]
        public string UsageType
        {
            get { return _usageType; }
            set
            {
                if (_usageType != value)
                {
                    _usageType = value;
                    OnPropertyChanged("UsageType");
                }
            }
        }
        private string _usageType;
    
        [DataMember]
        public Nullable<int> UserQuantity
        {
            get { return _userQuantity; }
            set
            {
                if (_userQuantity != value)
                {
                    _userQuantity = value;
                    OnPropertyChanged("UserQuantity");
                }
            }
        }
        private Nullable<int> _userQuantity;
    
        [DataMember]
        public Nullable<long> TotalSupply
        {
            get { return _totalSupply; }
            set
            {
                if (_totalSupply != value)
                {
                    _totalSupply = value;
                    OnPropertyChanged("TotalSupply");
                }
            }
        }
        private Nullable<long> _totalSupply;
    
        [DataMember]
        public Nullable<long> CurrentSupply
        {
            get { return _currentSupply; }
            set
            {
                if (_currentSupply != value)
                {
                    _currentSupply = value;
                    OnPropertyChanged("CurrentSupply");
                }
            }
        }
        private Nullable<long> _currentSupply;
    
        [DataMember]
        public string SupportExpert
        {
            get { return _supportExpert; }
            set
            {
                if (_supportExpert != value)
                {
                    _supportExpert = value;
                    OnPropertyChanged("SupportExpert");
                }
            }
        }
        private string _supportExpert;
    
        [DataMember]
        public string SalesExpert
        {
            get { return _salesExpert; }
            set
            {
                if (_salesExpert != value)
                {
                    _salesExpert = value;
                    OnPropertyChanged("SalesExpert");
                }
            }
        }
        private string _salesExpert;
    
        [DataMember]
        public Nullable<int> FixFaPrice
        {
            get { return _fixFaPrice; }
            set
            {
                if (_fixFaPrice != value)
                {
                    _fixFaPrice = value;
                    OnPropertyChanged("FixFaPrice");
                }
            }
        }
        private Nullable<int> _fixFaPrice;
    
        [DataMember]
        public Nullable<int> FixEnPrice
        {
            get { return _fixEnPrice; }
            set
            {
                if (_fixEnPrice != value)
                {
                    _fixEnPrice = value;
                    OnPropertyChanged("FixEnPrice");
                }
            }
        }
        private Nullable<int> _fixEnPrice;
    
        [DataMember]
        public string RecieveServerURL
        {
            get { return _recieveServerURL; }
            set
            {
                if (_recieveServerURL != value)
                {
                    _recieveServerURL = value;
                    OnPropertyChanged("RecieveServerURL");
                }
            }
        }
        private string _recieveServerURL;
    
        [DataMember]
        public Nullable<bool> HasBankAccount
        {
            get { return _hasBankAccount; }
            set
            {
                if (_hasBankAccount != value)
                {
                    _hasBankAccount = value;
                    OnPropertyChanged("HasBankAccount");
                }
            }
        }
        private Nullable<bool> _hasBankAccount;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
