//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tbl_UserAccount))]
    public partial class Tbl_UserAccountRole: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int AcsRoleCode
        {
            get { return _acsRoleCode; }
            set
            {
                if (_acsRoleCode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'AcsRoleCode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _acsRoleCode = value;
                    OnPropertyChanged("AcsRoleCode");
                }
            }
        }
        private int _acsRoleCode;
    
        [DataMember]
        public Nullable<int> AcsRoleParentId
        {
            get { return _acsRoleParentId; }
            set
            {
                if (_acsRoleParentId != value)
                {
                    _acsRoleParentId = value;
                    OnPropertyChanged("AcsRoleParentId");
                }
            }
        }
        private Nullable<int> _acsRoleParentId;
    
        [DataMember]
        public string AcsRoleEnName
        {
            get { return _acsRoleEnName; }
            set
            {
                if (_acsRoleEnName != value)
                {
                    _acsRoleEnName = value;
                    OnPropertyChanged("AcsRoleEnName");
                }
            }
        }
        private string _acsRoleEnName;
    
        [DataMember]
        public string AcsRoleFaName
        {
            get { return _acsRoleFaName; }
            set
            {
                if (_acsRoleFaName != value)
                {
                    _acsRoleFaName = value;
                    OnPropertyChanged("AcsRoleFaName");
                }
            }
        }
        private string _acsRoleFaName;
    
        [DataMember]
        public Nullable<int> AcsRolePrice
        {
            get { return _acsRolePrice; }
            set
            {
                if (_acsRolePrice != value)
                {
                    _acsRolePrice = value;
                    OnPropertyChanged("AcsRolePrice");
                }
            }
        }
        private Nullable<int> _acsRolePrice;
    
        [DataMember]
        public string AcsRoleDateFrom
        {
            get { return _acsRoleDateFrom; }
            set
            {
                if (_acsRoleDateFrom != value)
                {
                    _acsRoleDateFrom = value;
                    OnPropertyChanged("AcsRoleDateFrom");
                }
            }
        }
        private string _acsRoleDateFrom;
    
        [DataMember]
        public string AcsRoleDateTo
        {
            get { return _acsRoleDateTo; }
            set
            {
                if (_acsRoleDateTo != value)
                {
                    _acsRoleDateTo = value;
                    OnPropertyChanged("AcsRoleDateTo");
                }
            }
        }
        private string _acsRoleDateTo;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Tbl_UserAccount> Tbl_UserAccount
        {
            get
            {
                if (_tbl_UserAccount == null)
                {
                    _tbl_UserAccount = new TrackableCollection<Tbl_UserAccount>();
                    _tbl_UserAccount.CollectionChanged += FixupTbl_UserAccount;
                }
                return _tbl_UserAccount;
            }
            set
            {
                if (!ReferenceEquals(_tbl_UserAccount, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_tbl_UserAccount != null)
                    {
                        _tbl_UserAccount.CollectionChanged -= FixupTbl_UserAccount;
                    }
                    _tbl_UserAccount = value;
                    if (_tbl_UserAccount != null)
                    {
                        _tbl_UserAccount.CollectionChanged += FixupTbl_UserAccount;
                    }
                    OnNavigationPropertyChanged("Tbl_UserAccount");
                }
            }
        }
        private TrackableCollection<Tbl_UserAccount> _tbl_UserAccount;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_UserAccount.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_UserAccount(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Tbl_UserAccount item in e.NewItems)
                {
                    item.Tbl_UserAccountRole = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Tbl_UserAccount", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Tbl_UserAccount item in e.OldItems)
                {
                    if (ReferenceEquals(item.Tbl_UserAccountRole, this))
                    {
                        item.Tbl_UserAccountRole = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Tbl_UserAccount", item);
                    }
                }
            }
        }

        #endregion

    }
}
