//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(UsrCredit))]
    public partial class Tbl_Payment: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int PaymentCode
        {
            get { return _paymentCode; }
            set
            {
                if (_paymentCode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PaymentCode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _paymentCode = value;
                    OnPropertyChanged("PaymentCode");
                }
            }
        }
        private int _paymentCode;
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public Nullable<int> PayTypeCode
        {
            get { return _payTypeCode; }
            set
            {
                if (_payTypeCode != value)
                {
                    _payTypeCode = value;
                    OnPropertyChanged("PayTypeCode");
                }
            }
        }
        private Nullable<int> _payTypeCode;
    
        [DataMember]
        public Nullable<int> PayCommentCode
        {
            get { return _payCommentCode; }
            set
            {
                if (_payCommentCode != value)
                {
                    _payCommentCode = value;
                    OnPropertyChanged("PayCommentCode");
                }
            }
        }
        private Nullable<int> _payCommentCode;
    
        [DataMember]
        public Nullable<int> PaymentAmount
        {
            get { return _paymentAmount; }
            set
            {
                if (_paymentAmount != value)
                {
                    _paymentAmount = value;
                    OnPropertyChanged("PaymentAmount");
                }
            }
        }
        private Nullable<int> _paymentAmount;
    
        [DataMember]
        public Nullable<byte> PaymentDiscount
        {
            get { return _paymentDiscount; }
            set
            {
                if (_paymentDiscount != value)
                {
                    _paymentDiscount = value;
                    OnPropertyChanged("PaymentDiscount");
                }
            }
        }
        private Nullable<byte> _paymentDiscount;
    
        [DataMember]
        public string PayDisComment
        {
            get { return _payDisComment; }
            set
            {
                if (_payDisComment != value)
                {
                    _payDisComment = value;
                    OnPropertyChanged("PayDisComment");
                }
            }
        }
        private string _payDisComment;
    
        [DataMember]
        public string PaySerial
        {
            get { return _paySerial; }
            set
            {
                if (_paySerial != value)
                {
                    _paySerial = value;
                    OnPropertyChanged("PaySerial");
                }
            }
        }
        private string _paySerial;
    
        [DataMember]
        public string PaymentDate
        {
            get { return _paymentDate; }
            set
            {
                if (_paymentDate != value)
                {
                    _paymentDate = value;
                    OnPropertyChanged("PaymentDate");
                }
            }
        }
        private string _paymentDate;
    
        [DataMember]
        public string PayExpiredDate
        {
            get { return _payExpiredDate; }
            set
            {
                if (_payExpiredDate != value)
                {
                    _payExpiredDate = value;
                    OnPropertyChanged("PayExpiredDate");
                }
            }
        }
        private string _payExpiredDate;
    
        [DataMember]
        public Nullable<bool> PayFlag
        {
            get { return _payFlag; }
            set
            {
                if (_payFlag != value)
                {
                    _payFlag = value;
                    OnPropertyChanged("PayFlag");
                }
            }
        }
        private Nullable<bool> _payFlag;
    
        [DataMember]
        public Nullable<System.DateTime> PayDate
        {
            get { return _payDate; }
            set
            {
                if (_payDate != value)
                {
                    _payDate = value;
                    OnPropertyChanged("PayDate");
                }
            }
        }
        private Nullable<System.DateTime> _payDate;
    
        [DataMember]
        public string TransactionNumber
        {
            get { return _transactionNumber; }
            set
            {
                if (_transactionNumber != value)
                {
                    _transactionNumber = value;
                    OnPropertyChanged("TransactionNumber");
                }
            }
        }
        private string _transactionNumber;
    
        [DataMember]
        public Nullable<int> BankId
        {
            get { return _bankId; }
            set
            {
                if (_bankId != value)
                {
                    _bankId = value;
                    OnPropertyChanged("BankId");
                }
            }
        }
        private Nullable<int> _bankId;
    
        [DataMember]
        public string InvoiceNumber
        {
            get { return _invoiceNumber; }
            set
            {
                if (_invoiceNumber != value)
                {
                    _invoiceNumber = value;
                    OnPropertyChanged("InvoiceNumber");
                }
            }
        }
        private string _invoiceNumber;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public UsrCredit Tbl_UsrCredit
        {
            get { return _tbl_UsrCredit; }
            set
            {
                if (!ReferenceEquals(_tbl_UsrCredit, value))
                {
                    var previousValue = _tbl_UsrCredit;
                    _tbl_UsrCredit = value;
                    FixupTbl_UsrCredit(previousValue);
                    OnNavigationPropertyChanged("Tbl_UsrCredit");
                }
            }
        }
        private UsrCredit _tbl_UsrCredit;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_UsrCredit = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_UsrCredit(UsrCredit previousValue)
        {
            // This is the principal end in an association that performs cascade deletes.
            // Update the event listener to refer to the new dependent.
            if (previousValue != null)
            {
                ChangeTracker.ObjectStateChanging -= previousValue.HandleCascadeDelete;
            }
    
            if (Tbl_UsrCredit != null)
            {
                ChangeTracker.ObjectStateChanging += Tbl_UsrCredit.HandleCascadeDelete;
            }
    
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.Tbl_Payment, this))
            {
                previousValue.Tbl_Payment = null;
            }
    
            if (Tbl_UsrCredit != null)
            {
                Tbl_UsrCredit.Tbl_Payment = this;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_UsrCredit")
                    && (ChangeTracker.OriginalValues["Tbl_UsrCredit"] == Tbl_UsrCredit))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_UsrCredit");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_UsrCredit", previousValue);
                    // This is the principal end of an identifying association, so the dependent must be deleted when the relationship is removed.
                    // If the current state of the dependent is Added, the relationship can be changed without causing the dependent to be deleted.
                    if (previousValue != null && previousValue.ChangeTracker.State != ObjectState.Added)
                    {
                        previousValue.MarkAsDeleted();
                    }
                }
                if (Tbl_UsrCredit != null && !Tbl_UsrCredit.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_UsrCredit.StartTracking();
                }
            }
        }

        #endregion

    }
}
