//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class tbl_Extensible
    {
        public string IUsrId { get; set; }
        public string ServerURL { get; set; }
        public string UsageType { get; set; }
        public Nullable<int> UserQuantity { get; set; }
        public Nullable<long> TotalSupply { get; set; }
        public Nullable<long> CurrentSupply { get; set; }
        public string SupportExpert { get; set; }
        public string SalesExpert { get; set; }
        public Nullable<int> FixFaPrice { get; set; }
        public Nullable<int> FixEnPrice { get; set; }
        public string RecieveServerURL { get; set; }
        public Nullable<bool> HasBankAccount { get; set; }
        public string ConnectionString { get; set; }
    }
    
}
