//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    public partial class Tbl_RecieveSms: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string RcvSmsText
        {
            get { return _rcvSmsText; }
            set
            {
                if (_rcvSmsText != value)
                {
                    _rcvSmsText = value;
                    OnPropertyChanged("RcvSmsText");
                }
            }
        }
        private string _rcvSmsText;
    
        [DataMember]
        public string RcvsmsKeyWord
        {
            get { return _rcvsmsKeyWord; }
            set
            {
                if (_rcvsmsKeyWord != value)
                {
                    _rcvsmsKeyWord = value;
                    OnPropertyChanged("RcvsmsKeyWord");
                }
            }
        }
        private string _rcvsmsKeyWord;
    
        [DataMember]
        public string RcvSmsfrom
        {
            get { return _rcvSmsfrom; }
            set
            {
                if (_rcvSmsfrom != value)
                {
                    _rcvSmsfrom = value;
                    OnPropertyChanged("RcvSmsfrom");
                }
            }
        }
        private string _rcvSmsfrom;
    
        [DataMember]
        public string RcvSmsTo
        {
            get { return _rcvSmsTo; }
            set
            {
                if (_rcvSmsTo != value)
                {
                    _rcvSmsTo = value;
                    OnPropertyChanged("RcvSmsTo");
                }
            }
        }
        private string _rcvSmsTo;
    
        [DataMember]
        public string RcvSmsInteredDate
        {
            get { return _rcvSmsInteredDate; }
            set
            {
                if (_rcvSmsInteredDate != value)
                {
                    _rcvSmsInteredDate = value;
                    OnPropertyChanged("RcvSmsInteredDate");
                }
            }
        }
        private string _rcvSmsInteredDate;
    
        [DataMember]
        public string RcvSmsUDH
        {
            get { return _rcvSmsUDH; }
            set
            {
                if (_rcvSmsUDH != value)
                {
                    _rcvSmsUDH = value;
                    OnPropertyChanged("RcvSmsUDH");
                }
            }
        }
        private string _rcvSmsUDH;
    
        [DataMember]
        public string RcvsmsCharSet
        {
            get { return _rcvsmsCharSet; }
            set
            {
                if (_rcvsmsCharSet != value)
                {
                    _rcvsmsCharSet = value;
                    OnPropertyChanged("RcvsmsCharSet");
                }
            }
        }
        private string _rcvsmsCharSet;
    
        [DataMember]
        public string rcvSmsSmsC
        {
            get { return _rcvSmsSmsC; }
            set
            {
                if (_rcvSmsSmsC != value)
                {
                    _rcvSmsSmsC = value;
                    OnPropertyChanged("rcvSmsSmsC");
                }
            }
        }
        private string _rcvSmsSmsC;
    
        [DataMember]
        public string RcvSmsStatus
        {
            get { return _rcvSmsStatus; }
            set
            {
                if (_rcvSmsStatus != value)
                {
                    _rcvSmsStatus = value;
                    OnPropertyChanged("RcvSmsStatus");
                }
            }
        }
        private string _rcvSmsStatus;
    
        [DataMember]
        public string RcvSmsMessageID
        {
            get { return _rcvSmsMessageID; }
            set
            {
                if (_rcvSmsMessageID != value)
                {
                    _rcvSmsMessageID = value;
                    OnPropertyChanged("RcvSmsMessageID");
                }
            }
        }
        private string _rcvSmsMessageID;
    
        [DataMember]
        public string RcvSmsRuleID
        {
            get { return _rcvSmsRuleID; }
            set
            {
                if (_rcvSmsRuleID != value)
                {
                    _rcvSmsRuleID = value;
                    OnPropertyChanged("RcvSmsRuleID");
                }
            }
        }
        private string _rcvSmsRuleID;
    
        [DataMember]
        public string RcvSmsDeliveredTime
        {
            get { return _rcvSmsDeliveredTime; }
            set
            {
                if (_rcvSmsDeliveredTime != value)
                {
                    _rcvSmsDeliveredTime = value;
                    OnPropertyChanged("RcvSmsDeliveredTime");
                }
            }
        }
        private string _rcvSmsDeliveredTime;
    
        [DataMember]
        public Nullable<bool> RcvSmsReeded
        {
            get { return _rcvSmsReeded; }
            set
            {
                if (_rcvSmsReeded != value)
                {
                    _rcvSmsReeded = value;
                    OnPropertyChanged("RcvSmsReeded");
                }
            }
        }
        private Nullable<bool> _rcvSmsReeded;
    
        [DataMember]
        public string UsrId
        {
            get { return _usrId; }
            set
            {
                if (_usrId != value)
                {
                    _usrId = value;
                    OnPropertyChanged("UsrId");
                }
            }
        }
        private string _usrId;
    
        [DataMember]
        public int RecieveSMSId
        {
            get { return _recieveSMSId; }
            set
            {
                if (_recieveSMSId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'RecieveSMSId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _recieveSMSId = value;
                    OnPropertyChanged("RecieveSMSId");
                }
            }
        }
        private int _recieveSMSId;
    
        [DataMember]
        public Nullable<int> OperatorId
        {
            get { return _operatorId; }
            set
            {
                if (_operatorId != value)
                {
                    _operatorId = value;
                    OnPropertyChanged("OperatorId");
                }
            }
        }
        private Nullable<int> _operatorId;
    
        [DataMember]
        public Nullable<System.DateTime> RecieveDate
        {
            get { return _recieveDate; }
            set
            {
                if (_recieveDate != value)
                {
                    _recieveDate = value;
                    OnPropertyChanged("RecieveDate");
                }
            }
        }
        private Nullable<System.DateTime> _recieveDate;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
