//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class Tbl_BulkSendingDefinition
    {
        public int IBulkSendingDefCode { get; set; }
        public Nullable<int> IBulkMinQuantiy { get; set; }
        public Nullable<int> IBulkMaxQuantity { get; set; }
        public Nullable<int> IBulkSMSFaPrice { get; set; }
        public Nullable<int> IBulkSMSEnPrice { get; set; }
        public Nullable<int> IRcvPrice { get; set; }
        public string IUserID { get; set; }
    }
    
}
