//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class Ticket
    {
        public int TicketId { get; set; }
        public string Subject { get; set; }
        public string Body { get; set; }
        public int ResponsibleRole { get; set; }
        public string MessageFrom { get; set; }
        public byte TicketStatus { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int ParentId { get; set; }
        public byte[] AttachFile { get; set; }
        public string FileName { get; set; }
        public int PanelId { get; set; }
        public string ManagerId { get; set; }
        public string MessageTo { get; set; }
    }
    
}
