//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    public partial class UserInfo: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'IUsrId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public string AcsRoleEnName
        {
            get { return _acsRoleEnName; }
            set
            {
                if (_acsRoleEnName != value)
                {
                    _acsRoleEnName = value;
                    OnPropertyChanged("AcsRoleEnName");
                }
            }
        }
        private string _acsRoleEnName;
    
        [DataMember]
        public string AcsRoleFaName
        {
            get { return _acsRoleFaName; }
            set
            {
                if (_acsRoleFaName != value)
                {
                    _acsRoleFaName = value;
                    OnPropertyChanged("AcsRoleFaName");
                }
            }
        }
        private string _acsRoleFaName;
    
        [DataMember]
        public string ILineNumber
        {
            get { return _iLineNumber; }
            set
            {
                if (_iLineNumber != value)
                {
                    _iLineNumber = value;
                    OnPropertyChanged("ILineNumber");
                }
            }
        }
        private string _iLineNumber;
    
        [DataMember]
        public string ILineModuleNumber
        {
            get { return _iLineModuleNumber; }
            set
            {
                if (_iLineModuleNumber != value)
                {
                    _iLineModuleNumber = value;
                    OnPropertyChanged("ILineModuleNumber");
                }
            }
        }
        private string _iLineModuleNumber;
    
        [DataMember]
        public Nullable<bool> IUsrISAdmin
        {
            get { return _iUsrISAdmin; }
            set
            {
                if (_iUsrISAdmin != value)
                {
                    _iUsrISAdmin = value;
                    OnPropertyChanged("IUsrISAdmin");
                }
            }
        }
        private Nullable<bool> _iUsrISAdmin;
    
        [DataMember]
        public string IUsrIName
        {
            get { return _iUsrIName; }
            set
            {
                if (_iUsrIName != value)
                {
                    _iUsrIName = value;
                    OnPropertyChanged("IUsrIName");
                }
            }
        }
        private string _iUsrIName;
    
        [DataMember]
        public string IUsrPaswrd
        {
            get { return _iUsrPaswrd; }
            set
            {
                if (_iUsrPaswrd != value)
                {
                    _iUsrPaswrd = value;
                    OnPropertyChanged("IUsrPaswrd");
                }
            }
        }
        private string _iUsrPaswrd;
    
        [DataMember]
        public Nullable<bool> IUsrActive
        {
            get { return _iUsrActive; }
            set
            {
                if (_iUsrActive != value)
                {
                    _iUsrActive = value;
                    OnPropertyChanged("IUsrActive");
                }
            }
        }
        private Nullable<bool> _iUsrActive;
    
        [DataMember]
        public int AscRoleCode
        {
            get { return _ascRoleCode; }
            set
            {
                if (_ascRoleCode != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'AscRoleCode' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _ascRoleCode = value;
                    OnPropertyChanged("AscRoleCode");
                }
            }
        }
        private int _ascRoleCode;
    
        [DataMember]
        public string ICName
        {
            get { return _iCName; }
            set
            {
                if (_iCName != value)
                {
                    _iCName = value;
                    OnPropertyChanged("ICName");
                }
            }
        }
        private string _iCName;
    
        [DataMember]
        public string ICLName
        {
            get { return _iCLName; }
            set
            {
                if (_iCLName != value)
                {
                    _iCLName = value;
                    OnPropertyChanged("ICLName");
                }
            }
        }
        private string _iCLName;
    
        [DataMember]
        public string IUsrAccExpireDate
        {
            get { return _iUsrAccExpireDate; }
            set
            {
                if (_iUsrAccExpireDate != value)
                {
                    _iUsrAccExpireDate = value;
                    OnPropertyChanged("IUsrAccExpireDate");
                }
            }
        }
        private string _iUsrAccExpireDate;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
