//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class UserAccount
    {
        public UserAccount()
        {
            this.Bulks = new HashSet<BulkAcc>();
            this.Tbl_LineNumber = new HashSet<linenumber>();
        }
    
        public int IUsrAccCode { get; set; }
        public Nullable<int> IUserParentID { get; set; }
        public string IUsrManagerId { get; set; }
        public int IUsrCCode { get; set; }
        public int AscRoleCode { get; set; }
        public string IUsrId { get; set; }
        public string IUsrPaswrd { get; set; }
        public Nullable<bool> IUsrActive { get; set; }
        public Nullable<bool> IUsrSpesial { get; set; }
        public Nullable<bool> IUsrISAdmin { get; set; }
        public string IUsrIName { get; set; }
        public string IUsrAccCreatDate { get; set; }
        public string IUsrAccExpireDate { get; set; }
    
        public virtual ICollection<BulkAcc> Bulks { get; set; }
        public virtual ICollection<linenumber> Tbl_LineNumber { get; set; }
        public virtual Customers Tbl_Customers { get; set; }
    }
    
}
