//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Tbl_Payment))]
    public partial class UsrCredit: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public int PaymentId
        {
            get { return _paymentId; }
            set
            {
                if (_paymentId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'PaymentId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    if (!IsDeserializing)
                    {
                        if (Tbl_Payment != null && Tbl_Payment.PaymentCode != value)
                        {
                            Tbl_Payment = null;
                        }
                    }
                    _paymentId = value;
                    OnPropertyChanged("PaymentId");
                }
            }
        }
        private int _paymentId;
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public Nullable<int> ICreditAmount
        {
            get { return _iCreditAmount; }
            set
            {
                if (_iCreditAmount != value)
                {
                    _iCreditAmount = value;
                    OnPropertyChanged("ICreditAmount");
                }
            }
        }
        private Nullable<int> _iCreditAmount;
    
        [DataMember]
        public Nullable<int> ISMSFaPrice
        {
            get { return _iSMSFaPrice; }
            set
            {
                if (_iSMSFaPrice != value)
                {
                    _iSMSFaPrice = value;
                    OnPropertyChanged("ISMSFaPrice");
                }
            }
        }
        private Nullable<int> _iSMSFaPrice;
    
        [DataMember]
        public Nullable<int> ISMSEnPrice
        {
            get { return _iSMSEnPrice; }
            set
            {
                if (_iSMSEnPrice != value)
                {
                    _iSMSEnPrice = value;
                    OnPropertyChanged("ISMSEnPrice");
                }
            }
        }
        private Nullable<int> _iSMSEnPrice;
    
        [DataMember]
        public Nullable<int> IRcvSmsPrice
        {
            get { return _iRcvSmsPrice; }
            set
            {
                if (_iRcvSmsPrice != value)
                {
                    _iRcvSmsPrice = value;
                    OnPropertyChanged("IRcvSmsPrice");
                }
            }
        }
        private Nullable<int> _iRcvSmsPrice;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public Tbl_Payment Tbl_Payment
        {
            get { return _tbl_Payment; }
            set
            {
                if (!ReferenceEquals(_tbl_Payment, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added && value != null)
                    {
                        // This the dependent end of an identifying relationship, so the principal end cannot be changed if it is already set,
                        // otherwise it can only be set to an entity with a primary key that is the same value as the dependent's foreign key.
                        if (PaymentId != value.PaymentCode)
                        {
                            throw new InvalidOperationException("The principal end of an identifying relationship can only be changed when the dependent end is in the Added state.");
                        }
                    }
                    var previousValue = _tbl_Payment;
                    _tbl_Payment = value;
                    FixupTbl_Payment(previousValue);
                    OnNavigationPropertyChanged("Tbl_Payment");
                }
            }
        }
        private Tbl_Payment _tbl_Payment;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        // This entity type is the dependent end in at least one association that performs cascade deletes.
        // This event handler will process notifications that occur when the principal end is deleted.
        internal void HandleCascadeDelete(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                this.MarkAsDeleted();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Tbl_Payment = null;
        }

        #endregion

        #region Association Fixup
    
        private void FixupTbl_Payment(Tbl_Payment previousValue)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (previousValue != null && ReferenceEquals(previousValue.Tbl_UsrCredit, this))
            {
                previousValue.Tbl_UsrCredit = null;
            }
    
            if (Tbl_Payment != null)
            {
                Tbl_Payment.Tbl_UsrCredit = this;
                PaymentId = Tbl_Payment.PaymentCode;
            }
    
            if (ChangeTracker.ChangeTrackingEnabled)
            {
                if (ChangeTracker.OriginalValues.ContainsKey("Tbl_Payment")
                    && (ChangeTracker.OriginalValues["Tbl_Payment"] == Tbl_Payment))
                {
                    ChangeTracker.OriginalValues.Remove("Tbl_Payment");
                }
                else
                {
                    ChangeTracker.RecordOriginalValue("Tbl_Payment", previousValue);
                }
                if (Tbl_Payment != null && !Tbl_Payment.ChangeTracker.ChangeTrackingEnabled)
                {
                    Tbl_Payment.StartTracking();
                }
            }
        }

        #endregion

    }
}
