//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class VASContent
    {
        public int Id { get; set; }
        public string Body { get; set; }
        public int VASServiceId { get; set; }
        public int SortIndex { get; set; }
        public Nullable<bool> IsNew { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ContentName { get; set; }
    
        public virtual VASService VASService { get; set; }
    }
    
}
