//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace SSB.Service.Core
{
    public partial class VASService
    {
        public VASService()
        {
            this.VASContent = new HashSet<VASContent>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string PardisServiceId { get; set; }
        public int Price { get; set; }
        public string UserId { get; set; }
        public Nullable<bool> IsPublished { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int DefaultPerDay { get; set; }
        public Nullable<int> DefaultTimePeriod { get; set; }
        public string LineNumber { get; set; }
        public string ActiveKeyword { get; set; }
        public string DeactiveKeyword { get; set; }
        public Nullable<int> SendType { get; set; }
        public Nullable<int> ChargType { get; set; }
        public Nullable<int> ServiceType { get; set; }
        public Nullable<int> FreeContentCount { get; set; }
        public string WelcomeMessage { get; set; }
        public string ResignMessage { get; set; }
        public string DeactivateMessage { get; set; }
        public string MCIServiceId { get; set; }
        public Nullable<int> TCOperator { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public string InternalPardisId { get; set; }
    
        public virtual ICollection<VASContent> VASContent { get; set; }
    }
    
}
