//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace SSB.Service.Core
{
    [DataContract(IsReference = true)]
    public partial class View_Tbl_SentSMS: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Primitive Properties
    
        [DataMember]
        public long MagfaSmsId
        {
            get { return _magfaSmsId; }
            set
            {
                if (_magfaSmsId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'MagfaSmsId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _magfaSmsId = value;
                    OnPropertyChanged("MagfaSmsId");
                }
            }
        }
        private long _magfaSmsId;
    
        [DataMember]
        public string ISMSText
        {
            get { return _iSMSText; }
            set
            {
                if (_iSMSText != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'ISMSText' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _iSMSText = value;
                    OnPropertyChanged("ISMSText");
                }
            }
        }
        private string _iSMSText;
    
        [DataMember]
        public string ISendingDate
        {
            get { return _iSendingDate; }
            set
            {
                if (_iSendingDate != value)
                {
                    _iSendingDate = value;
                    OnPropertyChanged("ISendingDate");
                }
            }
        }
        private string _iSendingDate;
    
        [DataMember]
        public string ISendingTime
        {
            get { return _iSendingTime; }
            set
            {
                if (_iSendingTime != value)
                {
                    _iSendingTime = value;
                    OnPropertyChanged("ISendingTime");
                }
            }
        }
        private string _iSendingTime;
    
        [DataMember]
        public string ISenderNumber
        {
            get { return _iSenderNumber; }
            set
            {
                if (_iSenderNumber != value)
                {
                    _iSenderNumber = value;
                    OnPropertyChanged("ISenderNumber");
                }
            }
        }
        private string _iSenderNumber;
    
        [DataMember]
        public string IReciverNumber
        {
            get { return _iReciverNumber; }
            set
            {
                if (_iReciverNumber != value)
                {
                    _iReciverNumber = value;
                    OnPropertyChanged("IReciverNumber");
                }
            }
        }
        private string _iReciverNumber;
    
        [DataMember]
        public string ISMSStatuse
        {
            get { return _iSMSStatuse; }
            set
            {
                if (_iSMSStatuse != value)
                {
                    _iSMSStatuse = value;
                    OnPropertyChanged("ISMSStatuse");
                }
            }
        }
        private string _iSMSStatuse;
    
        [DataMember]
        public string IUsrId
        {
            get { return _iUsrId; }
            set
            {
                if (_iUsrId != value)
                {
                    _iUsrId = value;
                    OnPropertyChanged("IUsrId");
                }
            }
        }
        private string _iUsrId;
    
        [DataMember]
        public Nullable<int> ISMSStatusCode
        {
            get { return _iSMSStatusCode; }
            set
            {
                if (_iSMSStatusCode != value)
                {
                    _iSMSStatusCode = value;
                    OnPropertyChanged("ISMSStatusCode");
                }
            }
        }
        private Nullable<int> _iSMSStatusCode;
    
        [DataMember]
        public Nullable<int> Priority
        {
            get { return _priority; }
            set
            {
                if (_priority != value)
                {
                    _priority = value;
                    OnPropertyChanged("Priority");
                }
            }
        }
        private Nullable<int> _priority;
    
        [DataMember]
        public Nullable<int> PriorityStatus
        {
            get { return _priorityStatus; }
            set
            {
                if (_priorityStatus != value)
                {
                    _priorityStatus = value;
                    OnPropertyChanged("PriorityStatus");
                }
            }
        }
        private Nullable<int> _priorityStatus;
    
        [DataMember]
        public System.Guid Id
        {
            get { return _id; }
            set
            {
                if (_id != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Id' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private System.Guid _id;
    
        [DataMember]
        public int OperatorId
        {
            get { return _operatorId; }
            set
            {
                if (_operatorId != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'OperatorId' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _operatorId = value;
                    OnPropertyChanged("OperatorId");
                }
            }
        }
        private int _operatorId;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
        }

        #endregion

    }
}
